var text = '{ "biouser" : ' + 
'["https://github.com/0u812",'+
'"https://github.com/21zhangqiong",'+
'"https://github.com/4ment",'+
'"https://github.com/4ureliek",'+
'"https://github.com/7omasz",'+
'"https://github.com/AbhijitBadve",'+
'"https://github.com/Acribbs",'+
'"https://github.com/AlastairKerr",'+
'"https://github.com/AllonKleinLab",'+
'"https://github.com/Amoula1",'+
'"https://github.com/AnaPoets",'+
'"https://github.com/AndreasHeger",'+
'"https://github.com/AnjaSophieKiesel",'+
'"https://github.com/AnnaMatuszynska",'+
'"https://github.com/AnneCarpenter",'+
'"https://github.com/AntonioJBT",'+
'"https://github.com/ArtRand",'+
'"https://github.com/ArunasRadzvilavicius",'+
'"https://github.com/AtzeDeVries",'+
'"https://github.com/AugustT",'+
'"https://github.com/Blahah",'+
'"https://github.com/Bohdan-Khomtchouk",'+
'"https://github.com/Bonder-MJ",'+
'"https://github.com/BradCavinder",'+
'"https://github.com/CGRL-QB3-UCBerkeley",'+
'"https://github.com/Caetanods",'+
'"https://github.com/Caged",'+
'"https://github.com/CaioFreire",'+
'"https://github.com/ChaoPang",'+
'"https://github.com/Charlie-George",'+
'"https://github.com/Chris1221",'+
'"https://github.com/ChrisHIV",'+
'"https://github.com/ChristopherWilks",'+
'"https://github.com/CodingCat",'+
'"https://github.com/Compute5",'+
'"https://github.com/D",'+
'"https://github.com/DASpringate",'+
'"https://github.com/DL42",'+
'"https://github.com/DNAworker",'+
'"https://github.com/DRL",'+
'"https://github.com/DanChitwood",'+
'"https://github.com/DarwinW13",'+
'"https://github.com/DashaZhernakova",'+
'"https://github.com/DeveauP",'+
'"https://github.com/DiegoCambuy",'+
'"https://github.com/EDiLD",'+
'"https://github.com/EarnshawLab",'+
'"https://github.com/ElDeveloper",'+
'"https://github.com/EmanuelGoncalves",'+
'"https://github.com/Ettwiller",'+
'"https://github.com/FaustFrankenstein",'+
'"https://github.com/Fei-Lu",'+
'"https://github.com/FrancescaMancini",'+
'"https://github.com/FrankD",'+
'"https://github.com/Frencil",'+
'"https://github.com/GGiecold",'+
'"https://github.com/GNilsonne",'+
'"https://github.com/GPowney",'+
'"https://github.com/GaelVaroquaux",'+
'"https://github.com/Garyfallidis",'+
'"https://github.com/Generade-nl",'+
'"https://github.com/Gerbenvandervries",'+
'"https://github.com/Gibbsdavidl",'+
'"https://github.com/GiliG",'+
'"https://github.com/H1D",'+
'"https://github.com/HGID",'+
'"https://github.com/HioBeen",'+
'"https://github.com/Honghan",'+
'"https://github.com/HongjianLi",'+
'"https://github.com/Horta",'+
'"https://github.com/HrWangChengdu",'+
'"https://github.com/IZakirzyanov",'+
'"https://github.com/IanSudbery",'+
'"https://github.com/Ironholds",'+
'"https://github.com/JBed",'+
'"https://github.com/JWinawer",'+
'"https://github.com/JenCabral",'+
'"https://github.com/JeremyHorst",'+
'"https://github.com/Jfortin1",'+
'"https://github.com/JohnCEarls",'+
'"https://github.com/JohnEPool",'+
'"https://github.com/JohnReid",'+
'"https://github.com/Jorge-C",'+
'"https://github.com/JovMaksimovic",'+
'"https://github.com/KaneLab",'+
'"https://github.com/KatyBrown",'+
'"https://github.com/KoenHerten",'+
'"https://github.com/LHMarshall",'+
'"https://github.com/LTLA",'+
'"https://github.com/LaoZZZZZ",'+
'"https://github.com/LeeKamentsky",'+
'"https://github.com/Lestropie",'+
'"https://github.com/LiamDBailey",'+
'"https://github.com/Liuy12",'+
'"https://github.com/M42",'+
'"https://github.com/MManee",'+
'"https://github.com/MarkRobbo",'+
'"https://github.com/MartinFXP",'+
'"https://github.com/Martinsos",'+
'"https://github.com/Mathelab",'+
'"https://github.com/MattDrew",'+
'"https://github.com/MattHartfield",'+
'"https://github.com/Microbiology",'+
'"https://github.com/MikeAxtell",'+
'"https://github.com/MikeDMorgan",'+
'"https://github.com/MoHeydarian",'+
'"https://github.com/MonkeyLB",'+
'"https://github.com/MrCreosote",'+
'"https://github.com/MulletLab",'+
'"https://github.com/NeilPearson",'+
'"https://github.com/Nic-Nic",'+
'"https://github.com/OmnesRes",'+
'"https://github.com/Pas-Kapli",'+
'"https://github.com/PatrickDeelen",'+
'"https://github.com/PeteHaitch",'+
'"https://github.com/PeterDee",'+
'"https://github.com/PietaSchofield",'+
'"https://github.com/PoisonAlien",'+
'"https://github.com/RBankoff",'+
'"https://github.com/RCollins13",'+
'"https://github.com/RJMW",'+
'"https://github.com/Relequestual",'+
'"https://github.com/RemarkablyAverage",'+
'"https://github.com/RoanKanninga",'+
'"https://github.com/SRenan",'+
'"https://github.com/Sang33ta",'+
'"https://github.com/Sashkow",'+
'"https://github.com/Sephiroth1st",'+
'"https://github.com/ShantaoL",'+
'"https://github.com/SiminaB",'+
'"https://github.com/SoapZA",'+
'"https://github.com/SoyeonA",'+
'"https://github.com/StarvingMarvin",'+
'"https://github.com/StefanReuscher",'+
'"https://github.com/StephenTanner",'+
'"https://github.com/SusannaSansone",'+
'"https://github.com/Swandog",'+
'"https://github.com/SylvainCorlay",'+
'"https://github.com/Tabima",'+
'"https://github.com/Tharon-C",'+
'"https://github.com/TheaWhitman",'+
'"https://github.com/ThomasMiconi",'+
'"https://github.com/TomSmithCGAT",'+
'"https://github.com/TommyBlanchard",'+
'"https://github.com/Tomnl",'+
'"https://github.com/WanwanGe",'+
'"https://github.com/WeiqiangZhou",'+
'"https://github.com/XiongzhiChen",'+
'"https://github.com/Y-Lammers",'+
'"https://github.com/Yves-CHEN",'+
'"https://github.com/ZhiGroup",'+
'"https://github.com/Zigur",'+
'"https://github.com/ZihengJiang",'+
'"https://github.com/a-teufel",'+
'"https://github.com/abaghan",'+
'"https://github.com/abehr",'+
'"https://github.com/ablewhiskey",'+
'"https://github.com/abramovitchMSU",'+
'"https://github.com/abremges",'+
'"https://github.com/abrown25",'+
'"https://github.com/ackman678",'+
'"https://github.com/acoffman",'+
'"https://github.com/ad3002",'+
'"https://github.com/adamallo",'+
'"https://github.com/adamewing",'+
'"https://github.com/adamhsparks",'+
'"https://github.com/adamian",'+
'"https://github.com/adaptivegenome",'+
'"https://github.com/adelavega",'+
'"https://github.com/admiral-chen",'+
'"https://github.com/adrinjalali",'+
'"https://github.com/adsteen",'+
'"https://github.com/aecker",'+
'"https://github.com/afif-elghraoui",'+
'"https://github.com/afilipch",'+
'"https://github.com/afolarin",'+
'"https://github.com/afraser",'+
'"https://github.com/agbeltran",'+
'"https://github.com/agordon",'+
'"https://github.com/ags-wsu",'+
'"https://github.com/ahmadia",'+
'"https://github.com/ahoenselaar",'+
'"https://github.com/aileli",'+
'"https://github.com/aivelo",'+
'"https://github.com/ajbass",'+
'"https://github.com/ajitjohnson",'+
'"https://github.com/akahles",'+
'"https://github.com/akloetgen",'+
'"https://github.com/akourlaiev",'+
'"https://github.com/alanzos",'+
'"https://github.com/aldro61",'+
'"https://github.com/alegarra",'+
'"https://github.com/alexanderboulgakov",'+
'"https://github.com/alexginsca",'+
'"https://github.com/alexis-roche",'+
'"https://github.com/alexloboda",'+
'"https://github.com/alexviiia",'+
'"https://github.com/alipaquette",'+
'"https://github.com/alizrrao",'+
'"https://github.com/alneberg",'+
'"https://github.com/alyssafrazee",'+
'"https://github.com/amal-ghamdi",'+
'"https://github.com/amanbadhwar",'+
'"https://github.com/amcdavid",'+
'"https://github.com/amirrezaw",'+
'"https://github.com/amkozlov",'+
'"https://github.com/ammodramus",'+
'"https://github.com/amonida",'+
'"https://github.com/anandsethuraman",'+
'"https://github.com/andand",'+
'"https://github.com/andfoy",'+
'"https://github.com/andreagobbi",'+
'"https://github.com/andreas-schlicker",'+
'"https://github.com/andrewjdyck",'+
'"https://github.com/andrewjesaitis",'+
'"https://github.com/andrewjpage",'+
'"https://github.com/andrewsu",'+
'"https://github.com/andrewyatz",'+
'"https://github.com/andrwb",'+
'"https://github.com/andyljones",'+
'"https://github.com/angela-tam",'+
'"https://github.com/anilthanki",'+
'"https://github.com/ansariazim",'+
'"https://github.com/antinucleon",'+
'"https://github.com/anton-khodak",'+
'"https://github.com/aparkin",'+
'"https://github.com/apdavison",'+
'"https://github.com/aphillippy",'+
'"https://github.com/araksm",'+
'"https://github.com/archmageirvine",'+
'"https://github.com/arcoenen",'+
'"https://github.com/ariddell",'+
'"https://github.com/ariutta",'+
'"https://github.com/arlin",'+
'"https://github.com/armish",'+
'"https://github.com/arokem",'+
'"https://github.com/arq5x",'+
'"https://github.com/ashutoshkpandey",'+
'"https://github.com/asifrim",'+
'"https://github.com/asl",'+
'"https://github.com/asncd",'+
'"https://github.com/assaron",'+
'"https://github.com/at7",'+
'"https://github.com/atifrahman",'+
'"https://github.com/atredennick",'+
'"https://github.com/au-bios",'+
'"https://github.com/audy",'+
'"https://github.com/avullo",'+
'"https://github.com/aweimann",'+
'"https://github.com/awz",'+
'"https://github.com/b-steve",'+
'"https://github.com/baharpan",'+
'"https://github.com/baillielab",'+
'"https://github.com/baj12",'+
'"https://github.com/balaur",'+
'"https://github.com/balhoff",'+
'"https://github.com/balicea",'+
'"https://github.com/bannanc",'+
'"https://github.com/bartcharbon",'+
'"https://github.com/bas-rustenburg",'+
'"https://github.com/bbanbury",'+
'"https://github.com/bbarad",'+
'"https://github.com/bbimber",'+
'"https://github.com/bbitarello",'+
'"https://github.com/bbsunchen",'+
'"https://github.com/bderickson",'+
'"https://github.com/behrimg",'+
'"https://github.com/benaug",'+
'"https://github.com/benbowen",'+
'"https://github.com/bendmorris",'+
'"https://github.com/benfulcher",'+
'"https://github.com/benjaminhgood",'+
'"https://github.com/benjeffery",'+
'"https://github.com/benjjneb",'+
'"https://github.com/benpruitt",'+
'"https://github.com/bensutherland",'+
'"https://github.com/benwilson87",'+
'"https://github.com/bergeycm",'+
'"https://github.com/bethac07",'+
'"https://github.com/bgruening",'+
'"https://github.com/bhaibeka",'+
'"https://github.com/bharath-cchmc",'+
'"https://github.com/bheavner",'+
'"https://github.com/binarybottle",'+
'"https://github.com/binaypanda",'+
'"https://github.com/bioinfo-ut",'+
'"https://github.com/bioinfonm",'+
'"https://github.com/bjclavijo",'+
'"https://github.com/bjeurissen",'+
'"https://github.com/bjornwallner",'+
'"https://github.com/blahah",'+
'"https://github.com/blakeweb",'+
'"https://github.com/blasseigne",'+
'"https://github.com/blekhmanlab",'+
'"https://github.com/blink1073",'+
'"https://github.com/blopker",'+
'"https://github.com/bmbolstad",'+
'"https://github.com/bmvdgeijn",'+
'"https://github.com/bnbowman",'+
'"https://github.com/bneron",'+
'"https://github.com/bobcottingham",'+
'"https://github.com/bobular",'+
'"https://github.com/bomeara",'+
'"https://github.com/bondlab",'+
'"https://github.com/bosonogi",'+
'"https://github.com/bpbond",'+
'"https://github.com/bqminh",'+
'"https://github.com/bradleylab",'+
'"https://github.com/brainstorm",'+
'"https://github.com/brandonlind",'+
'"https://github.com/brantfaircloth",'+
'"https://github.com/braymp",'+
'"https://github.com/brentp",'+
'"https://github.com/brettbj",'+
'"https://github.com/brettin",'+
'"https://github.com/brianjohnhaas",'+
'"https://github.com/brianwalenz",'+
'"https://github.com/briehl",'+
'"https://github.com/briehm",'+
'"https://github.com/brielin",'+
'"https://github.com/brookehus",'+
'"https://github.com/brummett",'+
'"https://github.com/bsipos",'+
'"https://github.com/bulik",'+
'"https://github.com/buske",'+
'"https://github.com/bwalsh",'+
'"https://github.com/c1ndygao",'+
'"https://github.com/cangermueller",'+
'"https://github.com/carolinecolijn",'+
'"https://github.com/carrillo",'+
'"https://github.com/cashalow",'+
'"https://github.com/cashoes",'+
'"https://github.com/cassiedoll",'+
'"https://github.com/catavallejos",'+
'"https://github.com/cawaltrip",'+
'"https://github.com/cbahlai",'+
'"https://github.com/cbergman",'+
'"https://github.com/cblakkan",'+
'"https://github.com/cboettig",'+
'"https://github.com/cbrueffer",'+
'"https://github.com/cc2qe",'+
'"https://github.com/ccordoba12",'+
'"https://github.com/ccraddock",'+
'"https://github.com/ccshao",'+
'"https://github.com/cdansereau",'+
'"https://github.com/ceyhuneksin",'+
'"https://github.com/cfitz",'+
'"https://github.com/cfriedline",'+
'"https://github.com/cgreene",'+
'"https://github.com/champost",'+
'"https://github.com/chapmanb",'+
'"https://github.com/chaselgrove",'+
'"https://github.com/chawillia",'+
'"https://github.com/chedonat",'+
'"https://github.com/chiasto",'+
'"https://github.com/chienchi",'+
'"https://github.com/chiggum",'+
'"https://github.com/chr1swallace",'+
'"https://github.com/chrisamiller",'+
'"https://github.com/chrisfilo",'+
'"https://github.com/chrishah",'+
'"https://github.com/chrisprobert",'+
'"https://github.com/chrisquince",'+
'"https://github.com/chunhungyeh",'+
'"https://github.com/cianodonnell",'+
'"https://github.com/ciiram",'+
'"https://github.com/ckinzthompson",'+
'"https://github.com/clairemcwhite",'+
'"https://github.com/clippert",'+
'"https://github.com/cmagnabosco",'+
'"https://github.com/cmaumet",'+
'"https://github.com/cmhill",'+
'"https://github.com/cmungall",'+
'"https://github.com/cndewey",'+
'"https://github.com/coalsont",'+
'"https://github.com/come-raczy",'+
'"https://github.com/constellates",'+
'"https://github.com/copester",'+
'"https://github.com/coreymhudson",'+
'"https://github.com/cotsapaslab",'+
'"https://github.com/croth1",'+
'"https://github.com/csieffert",'+
'"https://github.com/ctb",'+
'"https://github.com/ctharve",'+
'"https://github.com/ctsa",'+
'"https://github.com/cure",'+
'"https://github.com/cuttlefishh",'+
'"https://github.com/cwidmer",'+
'"https://github.com/cwigington3",'+
'"https://github.com/cxhernandez",'+
'"https://github.com/cyenyxe",'+
'"https://github.com/dad",'+
'"https://github.com/dalexander",'+
'"https://github.com/dallagi",'+
'"https://github.com/dalthviz",'+
'"https://github.com/damienArnol",'+
'"https://github.com/dan-blanchard",'+
'"https://github.com/dandavison",'+
'"https://github.com/danielolson5",'+
'"https://github.com/danielriosgarza",'+
'"https://github.com/danilinares",'+
'"https://github.com/danimag",'+
'"https://github.com/dankoc",'+
'"https://github.com/danlwarren",'+
'"https://github.com/dannon",'+
'"https://github.com/danrdanny",'+
'"https://github.com/danstaines",'+
'"https://github.com/danweflen",'+
'"https://github.com/davek44",'+
'"https://github.com/davelunt",'+
'"https://github.com/david-borchers",'+
'"https://github.com/david-cgat",'+
'"https://github.com/david940408",'+
'"https://github.com/davidaknowles",'+
'"https://github.com/daviddao",'+
'"https://github.com/davidesmith",'+
'"https://github.com/davidheijkamp",'+
'"https://github.com/davidlmobley",'+
'"https://github.com/davidr",'+
'"https://github.com/davidrasm",'+
'"https://github.com/davidzchen",'+
'"https://github.com/daviesrob",'+
'"https://github.com/davisagli",'+
'"https://github.com/dbensasson",'+
'"https://github.com/dbgoodman",'+
'"https://github.com/dcgerard",'+
'"https://github.com/dchristiaens",'+
'"https://github.com/dcjones",'+
'"https://github.com/dcolligan",'+
'"https://github.com/ddarriba",'+
'"https://github.com/ddofer",'+
'"https://github.com/deboraycb",'+
'"https://github.com/deeenes",'+
'"https://github.com/denis-yuen",'+
'"https://github.com/dennishendriksen",'+
'"https://github.com/dennisroberts71",'+
'"https://github.com/derekguan",'+
'"https://github.com/dereneaton",'+
'"https://github.com/deto",'+
'"https://github.com/dfporter",'+
'"https://github.com/dg13",'+
'"https://github.com/dglazer",'+
'"https://github.com/dhimmel",'+
'"https://github.com/dhkron",'+
'"https://github.com/dill",'+
'"https://github.com/dimenwarper",'+
'"https://github.com/dimitri-yatsenko",'+
'"https://github.com/dipetkov",'+
'"https://github.com/diriano",'+
'"https://github.com/dirmeier",'+
'"https://github.com/djcomlab",'+
'"https://github.com/djvanenckevort",'+
'"https://github.com/dkj",'+
'"https://github.com/dkoslicki",'+
'"https://github.com/dlaehnemann",'+
'"https://github.com/dlampart",'+
'"https://github.com/dleehr",'+
'"https://github.com/dlgeorge",'+
'"https://github.com/dlogan",'+
'"https://github.com/dmbryson",'+
'"https://github.com/dmontaner",'+
'"https://github.com/dnewkirk",'+
'"https://github.com/dogcaesar",'+
'"https://github.com/dohalloran",'+
'"https://github.com/donkeyshot",'+
'"https://github.com/donnacalhoun",'+
'"https://github.com/doricke",'+
'"https://github.com/douglasgscofield",'+
'"https://github.com/draffelt",'+
'"https://github.com/drchriscole",'+
'"https://github.com/droghetti",'+
'"https://github.com/dsjohnson",'+
'"https://github.com/dspeyer",'+
'"https://github.com/dtrapezoid",'+
'"https://github.com/dufeiyu",'+
'"https://github.com/dufourya",'+
'"https://github.com/duncantl",'+
'"https://github.com/dustinvtran",'+
'"https://github.com/dvallenet",'+
'"https://github.com/dwinter",'+
'"https://github.com/dzerbino",'+
'"https://github.com/e5c",'+
'"https://github.com/eamonnmag",'+
'"https://github.com/earcher",'+
'"https://github.com/ebelter",'+
'"https://github.com/ebolyen",'+
'"https://github.com/edliaw",'+
'"https://github.com/eduati",'+
'"https://github.com/edwins",'+
'"https://github.com/effigies",'+
'"https://github.com/egeeamu",'+
'"https://github.com/eiriniar",'+
'"https://github.com/ekg",'+
'"https://github.com/eldrid01",'+
'"https://github.com/eliotmiller",'+
'"https://github.com/elzbth",'+
'"https://github.com/emarinier",'+
'"https://github.com/emhart",'+
'"https://github.com/emjosephs",'+
'"https://github.com/emmenlau",'+
'"https://github.com/emreg00",'+
'"https://github.com/en99sy",'+
'"https://github.com/enormandeau",'+
'"https://github.com/ens-ap5",'+
'"https://github.com/ens-ba1",'+
'"https://github.com/ens-ds23",'+
'"https://github.com/ens-emily",'+
'"https://github.com/ens-hsr",'+
'"https://github.com/ens-lg4",'+
'"https://github.com/ens-lgil",'+
'"https://github.com/ens-ma7",'+
'"https://github.com/ens-sophie",'+
'"https://github.com/ens-st3",'+
'"https://github.com/epareja",'+
'"https://github.com/eparejatobes",'+
'"https://github.com/epierson9",'+
'"https://github.com/episurg",'+
'"https://github.com/erasche",'+
'"https://github.com/erex",'+
'"https://github.com/ericenns",'+
'"https://github.com/ericevans",'+
'"https://github.com/ericnovik",'+
'"https://github.com/ericschulz",'+
'"https://github.com/erikroos",'+
'"https://github.com/eriqande",'+
'"https://github.com/erscott",'+
'"https://github.com/erwinwinder",'+
'"https://github.com/esbeneickhardt",'+
'"https://github.com/etal",'+
'"https://github.com/ethanwhite",'+
'"https://github.com/eywalker",'+
'"https://github.com/ezralanglois",'+
'"https://github.com/fac2003",'+
'"https://github.com/fairmiracle",'+
'"https://github.com/famulare",'+
'"https://github.com/faraway1nspace",'+
'"https://github.com/fbreitwieser",'+
'"https://github.com/fbristow",'+
'"https://github.com/fchollet",'+
'"https://github.com/fcunningham",'+
'"https://github.com/fdtomasi",'+
'"https://github.com/feipaat",'+
'"https://github.com/fergalmartin",'+
'"https://github.com/ferracimo",'+
'"https://github.com/fgvieira",'+
'"https://github.com/figure002",'+
'"https://github.com/finkelsteinlab",'+
'"https://github.com/fjhheras",'+
'"https://github.com/fjug",'+
'"https://github.com/fklirono",'+
'"https://github.com/flass",'+
'"https://github.com/fleandr",'+
'"https://github.com/fliem",'+
'"https://github.com/flophys",'+
'"https://github.com/fluca",'+
'"https://github.com/footprint",'+
'"https://github.com/foreveremain",'+
'"https://github.com/fperez",'+
'"https://github.com/fpieters",'+
'"https://github.com/francescojm",'+
'"https://github.com/francoischouinard",'+
'"https://github.com/francopestilli",'+
'"https://github.com/frb-yousefi",'+
'"https://github.com/freerkvandijk",'+
'"https://github.com/friend1ws",'+
'"https://github.com/fripp",'+
'"https://github.com/fritzsedlazeck",'+
'"https://github.com/froggleston",'+
'"https://github.com/fruce-ki",'+
'"https://github.com/fstrozzi",'+
'"https://github.com/fukunagatsu",'+
'"https://github.com/fungs",'+
'"https://github.com/fusaroli",'+
'"https://github.com/fvandin",'+
'"https://github.com/fxia22",'+
'"https://github.com/gabraham",'+
'"https://github.com/gangwug",'+
'"https://github.com/gaoshanT",'+
'"https://github.com/gaow",'+
'"https://github.com/gauravbhatia1",'+
'"https://github.com/gavruskin",'+
'"https://github.com/gawbul",'+
'"https://github.com/gbradburd",'+
'"https://github.com/gc5k",'+
'"https://github.com/gconcepcion",'+
'"https://github.com/gdbzork",'+
'"https://github.com/gdevailly",'+
'"https://github.com/gdevenyi",'+
'"https://github.com/gecgooden",'+
'"https://github.com/geneva",'+
'"https://github.com/georgebyelas",'+
'"https://github.com/georgek",'+
'"https://github.com/gfinak",'+
'"https://github.com/gilles-didier",'+
'"https://github.com/giorap",'+
'"https://github.com/giraola",'+
'"https://github.com/gjbarton",'+
'"https://github.com/glebkuznetsov",'+
'"https://github.com/gmarcais",'+
'"https://github.com/gmauro",'+
'"https://github.com/gmiaslab",'+
'"https://github.com/gmichalareas",'+
'"https://github.com/gmoyerbrailean",'+
'"https://github.com/goanpeca",'+
'"https://github.com/gpu-pdl-nudt",'+
'"https://github.com/greeco",'+
'"https://github.com/gregcaporaso",'+
'"https://github.com/grettadarmstrong",'+
'"https://github.com/greysAcademicCode",'+
'"https://github.com/grunwald",'+
'"https://github.com/gwaygenomics",'+
'"https://github.com/ha0ye",'+
'"https://github.com/hacone",'+
'"https://github.com/hadjimy",'+
'"https://github.com/hadley",'+
'"https://github.com/hagenaue",'+
'"https://github.com/hailianghuang",'+
'"https://github.com/hammer",'+
'"https://github.com/happycodemonkey",'+
'"https://github.com/harmjanwestra",'+
'"https://github.com/hclimente",'+
'"https://github.com/hdetering",'+
'"https://github.com/hduijn",'+
'"https://github.com/health1987",'+
'"https://github.com/hechao0407",'+
'"https://github.com/herkulano",'+
'"https://github.com/hetong007",'+
'"https://github.com/hettling",'+
'"https://github.com/hitz",'+
'"https://github.com/hjk41",'+
'"https://github.com/hlapp",'+
'"https://github.com/hly89",'+
'"https://github.com/hmatsu1226",'+
'"https://github.com/hmenager",'+
'"https://github.com/hmorlon",'+
'"https://github.com/holgerhennig",'+
'"https://github.com/homonecloco",'+
'"https://github.com/homopolymer",'+
'"https://github.com/hongcui",'+
'"https://github.com/hotpxl",'+
'"https://github.com/hrichards",'+
'"https://github.com/huizhangucas",'+
'"https://github.com/huwenboshi",'+
'"https://github.com/huyue87",'+
'"https://github.com/hvaret",'+
'"https://github.com/hyphaltip",'+
'"https://github.com/iamciera",'+
'"https://github.com/ibartomeus",'+
'"https://github.com/identifiers-org",'+
'"https://github.com/igordot",'+
'"https://github.com/ihaque",'+
'"https://github.com/ihh",'+
'"https://github.com/ihodes",'+
'"https://github.com/ikwak2",'+
'"https://github.com/ilavidas",'+
'"https://github.com/ilveroluca",'+
'"https://github.com/indiagordon",'+
'"https://github.com/inodb",'+
'"https://github.com/interCM",'+
'"https://github.com/iosonofabio",'+
'"https://github.com/ipan",'+
'"https://github.com/ipw012",'+
'"https://github.com/iqbal-lab",'+
'"https://github.com/iskana",'+
'"https://github.com/iskandr",'+
'"https://github.com/isovic",'+
'"https://github.com/ivanov",'+
'"https://github.com/jackhump",'+
'"https://github.com/jaclyn-taroni",'+
'"https://github.com/jacobian1980",'+
'"https://github.com/jade-cheng",'+
'"https://github.com/jagajaga",'+
'"https://github.com/jairideout",'+
'"https://github.com/jakebiesinger",'+
'"https://github.com/jakob-wirbel",'+
'"https://github.com/jamescrall",'+
'"https://github.com/jameshensman",'+
'"https://github.com/jamesliley",'+
'"https://github.com/jameslyons",'+
'"https://github.com/janis680",'+
'"https://github.com/jaredo",'+
'"https://github.com/jarrodmillman",'+
'"https://github.com/jasonsahl",'+
'"https://github.com/jasonwalker80",'+
'"https://github.com/jasperlinthorst",'+
'"https://github.com/javelinjs",'+
'"https://github.com/javiergonzalezh",'+
'"https://github.com/jaymollica",'+
'"https://github.com/jaytlennon",'+
'"https://github.com/jbeckstr",'+
'"https://github.com/jbkinney",'+
'"https://github.com/jbloom",'+
'"https://github.com/jbpoline",'+
'"https://github.com/jburos",'+
'"https://github.com/jbyoder",'+
'"https://github.com/jcarrotzhang",'+
'"https://github.com/jchodera",'+
'"https://github.com/jcoffland",'+
'"https://github.com/jdelafon",'+
'"https://github.com/jdiedrichsen",'+
'"https://github.com/jdstorey",'+
'"https://github.com/jdtournier",'+
'"https://github.com/jedick",'+
'"https://github.com/jeetsukumaran",'+
'"https://github.com/jeldred",'+
'"https://github.com/jenniferliddle",'+
'"https://github.com/jennybc",'+
'"https://github.com/jeparson",'+
'"https://github.com/jeremyjliu",'+
'"https://github.com/jeremymcrae",'+
'"https://github.com/jermainewang",'+
'"https://github.com/jeromekelleher",'+
'"https://github.com/jessica-andreani",'+
'"https://github.com/jestill",'+
'"https://github.com/jethrojohnson",'+
'"https://github.com/jgabry",'+
'"https://github.com/jgurtowski",'+
'"https://github.com/jhawkey",'+
'"https://github.com/jhcepas",'+
'"https://github.com/jhollist",'+
'"https://github.com/jijiadong",'+
'"https://github.com/jimhester",'+
'"https://github.com/jingraham",'+
'"https://github.com/jitseniesen",'+
'"https://github.com/jkaralius",'+
'"https://github.com/jkenney9a",'+
'"https://github.com/jlaake",'+
'"https://github.com/jlehtoma",'+
'"https://github.com/jlpereira",'+
'"https://github.com/jmacdona",'+
'"https://github.com/jmarshall",'+
'"https://github.com/jmchilton",'+
'"https://github.com/jmcmichael",'+
'"https://github.com/jmcmurry",'+
'"https://github.com/jmkidd",'+
'"https://github.com/jnktsj",'+
'"https://github.com/jocelynnpearl",'+
'"https://github.com/joebathelt",'+
'"https://github.com/joelhsmth",'+
'"https://github.com/joepickrell",'+
'"https://github.com/joerivandervelde",'+
'"https://github.com/joewandy",'+
'"https://github.com/johndharrison",'+
'"https://github.com/johnomics",'+
'"https://github.com/johnworth",'+
'"https://github.com/jonemo",'+
'"https://github.com/jorruior",'+
'"https://github.com/josephryan",'+
'"https://github.com/joshuabhk",'+
'"https://github.com/jotwin",'+
'"https://github.com/jpellman",'+
'"https://github.com/jpillow",'+
'"https://github.com/jpritt",'+
'"https://github.com/jsalva",'+
'"https://github.com/jscaber",'+
'"https://github.com/jsharbrough",'+
'"https://github.com/jsilve24",'+
'"https://github.com/jstapleton",'+
'"https://github.com/jstjohn",'+
'"https://github.com/jts",'+
'"https://github.com/juettemann",'+
'"https://github.com/juhis",'+
'"https://github.com/julia326",'+
'"https://github.com/julien-roux",'+
'"https://github.com/julienfumey",'+
'"https://github.com/juyeongkim",'+
'"https://github.com/jwijffels",'+
'"https://github.com/jyu429",'+
'"https://github.com/kaazemi",'+
'"https://github.com/kakitone",'+
'"https://github.com/kalleknast",'+
'"https://github.com/kantale",'+
'"https://github.com/karl616",'+
'"https://github.com/karthik",'+
'"https://github.com/kassambara",'+
'"https://github.com/katherinef",'+
'"https://github.com/katholt",'+
'"https://github.com/kauralasoo",'+
'"https://github.com/kayeeyeung",'+
'"https://github.com/kazlauskis",'+
'"https://github.com/kbchoi-jax",'+
'"https://github.com/kbhoehn",'+
'"https://github.com/kbillis",'+
'"https://github.com/kbroman",'+
'"https://github.com/kc-lab",'+
'"https://github.com/kcranston",'+
'"https://github.com/kdmurray91",'+
'"https://github.com/kdrees",'+
'"https://github.com/kellieotto",'+
'"https://github.com/kellrott",'+
'"https://github.com/kendonB",'+
'"https://github.com/kendrickkay",'+
'"https://github.com/kern-lab",'+
'"https://github.com/ketch",'+
'"https://github.com/kevinushey",'+
'"https://github.com/khaug",'+
'"https://github.com/khayer",'+
'"https://github.com/khillion",'+
'"https://github.com/khramts",'+
'"https://github.com/kieranrcampbell",'+
'"https://github.com/kikkomep",'+
'"https://github.com/kiramt",'+
'"https://github.com/kislyuk",'+
'"https://github.com/kkdey",'+
'"https://github.com/kkellerlbl",'+
'"https://github.com/kleisb",'+
'"https://github.com/kloetzl",'+
'"https://github.com/kmckiern",'+
'"https://github.com/knausb",'+
'"https://github.com/koadman",'+
'"https://github.com/konradjk",'+
'"https://github.com/kristiyanto",'+
'"https://github.com/kruggles7",'+
'"https://github.com/ksahlin",'+
'"https://github.com/ksdrew",'+
'"https://github.com/kshefchek",'+
'"https://github.com/kshitijtayal",'+
'"https://github.com/ktrappe",'+
'"https://github.com/kuod",'+
'"https://github.com/kvougas",'+
'"https://github.com/kyleabeauchamp",'+
'"https://github.com/kylehamilton",'+
'"https://github.com/lamarck2008",'+
'"https://github.com/lanagarmire",'+
'"https://github.com/laserson",'+
'"https://github.com/laughedelic",'+
'"https://github.com/laurenemberson",'+
'"https://github.com/lawrennd",'+
'"https://github.com/lbaeten",'+
'"https://github.com/lcolladotor",'+
'"https://github.com/ldash",'+
'"https://github.com/leeper",'+
'"https://github.com/leereilly",'+
'"https://github.com/leffj",'+
'"https://github.com/lengning",'+
'"https://github.com/lenthomas",'+
'"https://github.com/lganel",'+
'"https://github.com/lh3",'+
'"https://github.com/lhhunghimself",'+
'"https://github.com/li-chen",'+
'"https://github.com/lingjie",'+
'"https://github.com/linsalrob",'+
'"https://github.com/linzx06",'+
'"https://github.com/ljosa",'+
'"https://github.com/ljyanesm",'+
'"https://github.com/llerussell",'+
'"https://github.com/llynn",'+
'"https://github.com/lmperry",'+
'"https://github.com/lmweber",'+
'"https://github.com/local-minimum",'+
'"https://github.com/loire",'+
'"https://github.com/lomereiter",'+
'"https://github.com/lorinanthony",'+
'"https://github.com/lp2",'+
'"https://github.com/lpfgarcia",'+
'"https://github.com/lrowe",'+
'"https://github.com/lryta",'+
'"https://github.com/lsncibb",'+
'"https://github.com/lstevison",'+
'"https://github.com/lucalianas",'+
'"https://github.com/lucapinello",'+
'"https://github.com/lucaswiman",'+
'"https://github.com/luisacutillo78",'+
'"https://github.com/luisibanez",'+
'"https://github.com/luoyunan",'+
'"https://github.com/lutzfischer",'+
'"https://github.com/luzgaral",'+
'"https://github.com/lvdmaaten",'+
'"https://github.com/lyd0527",'+
'"https://github.com/ma-compbio",'+
'"https://github.com/machinegun",'+
'"https://github.com/madprime",'+
'"https://github.com/magaliruffier",'+
'"https://github.com/magicDGS",'+
'"https://github.com/mahyam",'+
'"https://github.com/mailund",'+
'"https://github.com/malachig",'+
'"https://github.com/maljoras",'+
'"https://github.com/mandli",'+
'"https://github.com/manuelesimi",'+
'"https://github.com/manzilzaheer",'+
'"https://github.com/maplesond",'+
'"https://github.com/marco-brandizi",'+
'"https://github.com/marcus1487",'+
'"https://github.com/mariacamilaremolinagutierrez",'+
'"https://github.com/marianattestad",'+
'"https://github.com/marina-manrique",'+
'"https://github.com/markdunning",'+
'"https://github.com/markrobinsonuzh",'+
'"https://github.com/marta-",'+
'"https://github.com/martenson",'+
'"https://github.com/martin-steinegger",'+
'"https://github.com/martinosorb",'+
'"https://github.com/marvin-jens",'+
'"https://github.com/marvinboe",'+
'"https://github.com/mashbyPacBio",'+
'"https://github.com/massie",'+
'"https://github.com/mathii",'+
'"https://github.com/matthew-brett",'+
'"https://github.com/mattions",'+
'"https://github.com/mattjvincent",'+
'"https://github.com/mattsooknah",'+
'"https://github.com/mavenlin",'+
'"https://github.com/maxentile",'+
'"https://github.com/maxpietsch",'+
'"https://github.com/maziz2",'+
'"https://github.com/mbakke",'+
'"https://github.com/mbaudis",'+
'"https://github.com/mbdoud",'+
'"https://github.com/mbernste",'+
'"https://github.com/mbi2gs",'+
'"https://github.com/mbontrager",'+
'"https://github.com/mbrubake",'+
'"https://github.com/mbusby",'+
'"https://github.com/mbuzdalov",'+
'"https://github.com/mcallaway",'+
'"https://github.com/mdcao",'+
'"https://github.com/mdfortune",'+
'"https://github.com/mdijkstra",'+
'"https://github.com/mdrio",'+
'"https://github.com/mdylag",'+
'"https://github.com/meganllarsen",'+
'"https://github.com/melop",'+
'"https://github.com/memming",'+
'"https://github.com/mendessoares",'+
'"https://github.com/mercere99",'+
'"https://github.com/meren",'+
'"https://github.com/mevers",'+
'"https://github.com/mezera",'+
'"https://github.com/mfcovington",'+
'"https://github.com/mfiume",'+
'"https://github.com/mfumagalli",'+
'"https://github.com/mg14",'+
'"https://github.com/mgaldzic",'+
'"https://github.com/mgonzalezporta",'+
'"https://github.com/mhoff",'+
'"https://github.com/mhsieh",'+
'"https://github.com/mhuyck",'+
'"https://github.com/micheldumontier",'+
'"https://github.com/middleprofessor",'+
'"https://github.com/mih",'+
'"https://github.com/mikecroucher",'+
'"https://github.com/mikejiang",'+
'"https://github.com/mikel-egana-aranguren",'+
'"https://github.com/mikelove",'+
'"https://github.com/mikepolcari",'+
'"https://github.com/mikhail-dvorkin",'+
'"https://github.com/millanek",'+
'"https://github.com/milot-mirdita",'+
'"https://github.com/min110",'+
'"https://github.com/mitzimorris",'+
'"https://github.com/mjy",'+
'"https://github.com/mkempenaar",'+
'"https://github.com/mlandis",'+
'"https://github.com/mleibman",'+
'"https://github.com/mli",'+
'"https://github.com/mlin",'+
'"https://github.com/mmacpherson",'+
'"https://github.com/mmatschiner",'+
'"https://github.com/mmuscarella",'+
'"https://github.com/mohawkjohn",'+
'"https://github.com/molpopgen",'+
'"https://github.com/monicacecilia",'+
'"https://github.com/moold",'+
'"https://github.com/mourisl",'+
'"https://github.com/mp15",'+
'"https://github.com/mpdunne",'+
'"https://github.com/mpharrigan",'+
'"https://github.com/mpkocher",'+
'"https://github.com/mplass",'+
'"https://github.com/mqbpjfg2",'+
'"https://github.com/mrdrgz",'+
'"https://github.com/mreppell",'+
'"https://github.com/mrhanlon",'+
'"https://github.com/mrhunsaker",'+
'"https://github.com/mrmckain",'+
'"https://github.com/mrmin123",'+
'"https://github.com/mschilli87",'+
'"https://github.com/mschubert",'+
'"https://github.com/msettles",'+
'"https://github.com/mswertz",'+
'"https://github.com/mtakemiya",'+
'"https://github.com/mtw",'+
'"https://github.com/mu2013",'+
'"https://github.com/muffato",'+
'"https://github.com/muhligs",'+
'"https://github.com/murphycj",'+
'"https://github.com/murphydn",'+
'"https://github.com/mvboven",'+
'"https://github.com/mvdbeek",'+
'"https://github.com/mw55309",'+
'"https://github.com/mwaskom",'+
'"https://github.com/mwvaughn",'+
'"https://github.com/mz2",'+
'"https://github.com/mzwiessele",'+
'"https://github.com/najoshi",'+
'"https://github.com/naomiyamada",'+
'"https://github.com/narechan",'+
'"https://github.com/natefoo",'+
'"https://github.com/nathanmlim",'+
'"https://github.com/nchambwe",'+
'"https://github.com/nedelec",'+
'"https://github.com/nelas",'+
'"https://github.com/nellore",'+
'"https://github.com/nelson42",'+
'"https://github.com/nerdstrike",'+
'"https://github.com/nerobbin",'+
'"https://github.com/nfahlgren",'+
'"https://github.com/nfusi",'+
'"https://github.com/nghiavtr",'+
'"https://github.com/nh13",'+
'"https://github.com/nicholsn",'+
'"https://github.com/nickilott",'+
'"https://github.com/nignatiadis",'+
'"https://github.com/nilbus",'+
'"https://github.com/nluhmann",'+
'"https://github.com/nmatasci",'+
'"https://github.com/nmdavies",'+
'"https://github.com/nouyang-curoverse",'+
'"https://github.com/nsoranzo",'+
'"https://github.com/nstenz",'+
'"https://github.com/nthitz",'+
'"https://github.com/ntijanic",'+
'"https://github.com/nturaga",'+
'"https://github.com/nukappa",'+
'"https://github.com/nvalimak",'+
'"https://github.com/obigriffith",'+
'"https://github.com/oesteban",'+
'"https://github.com/oganm",'+
'"https://github.com/olsonanl",'+
'"https://github.com/ondovb",'+
'"https://github.com/opetchey",'+
'"https://github.com/orrzor",'+
'"https://github.com/osobh",'+
'"https://github.com/ostegle",'+
'"https://github.com/pablopareja",'+
'"https://github.com/pacbiodevnet",'+
'"https://github.com/pagnani",'+
'"https://github.com/pajanne",'+
'"https://github.com/paolotoldo",'+
'"https://github.com/paraiko",'+
'"https://github.com/parkag",'+
'"https://github.com/pasculorente",'+
'"https://github.com/paula-tataru",'+
'"https://github.com/pawni",'+
'"https://github.com/pb-devans",'+
'"https://github.com/pb-dyim",'+
'"https://github.com/pb-jchin",'+
'"https://github.com/pb-jlandolin",'+
'"https://github.com/pbastide",'+
'"https://github.com/pbellec",'+
'"https://github.com/pberkes",'+
'"https://github.com/pbjd",'+
'"https://github.com/pblischak",'+
'"https://github.com/pbrobst23",'+
'"https://github.com/pbruha",'+
'"https://github.com/pd3",'+
'"https://github.com/peabody124",'+
'"https://github.com/peastman",'+
'"https://github.com/pedroj",'+
'"https://github.com/peldax",'+
'"https://github.com/pellinglab",'+
'"https://github.com/pennekampster",'+
'"https://github.com/petercombs",'+
'"https://github.com/petrelharp",'+
'"https://github.com/pgleeson",'+
'"https://github.com/pgnelson",'+
'"https://github.com/pgrinaway",'+
'"https://github.com/philippmuench",'+
'"https://github.com/philres",'+
'"https://github.com/phrh",'+
'"https://github.com/pierpal",'+
'"https://github.com/piiswrong",'+
'"https://github.com/pimentel",'+
'"https://github.com/pjvandehaar",'+
'"https://github.com/pkaleta",'+
'"https://github.com/pkerpedjiev",'+
'"https://github.com/pkrusche",'+
'"https://github.com/pli888",'+
'"https://github.com/pliu55",'+
'"https://github.com/pluskid",'+
'"https://github.com/pmajka",'+
'"https://github.com/pmb59",'+
'"https://github.com/pmidford",'+
'"https://github.com/pneerincx",'+
'"https://github.com/pnlawlor",'+
'"https://github.com/poeli",'+
'"https://github.com/pommedeterresautee",'+
'"https://github.com/pontikos",'+
'"https://github.com/popgenomics",'+
'"https://github.com/portah",'+
'"https://github.com/ppgardne",'+
'"https://github.com/pranjan77",'+
'"https://github.com/praveen16",'+
'"https://github.com/proccaserra",'+
'"https://github.com/psarando",'+
'"https://github.com/psdehal",'+
'"https://github.com/pshved",'+
'"https://github.com/pstew",'+
'"https://github.com/psturmfels",'+
'"https://github.com/psy106616",'+
'"https://github.com/qfma",'+
'"https://github.com/quantixed",'+
'"https://github.com/quantum-man",'+
'"https://github.com/r3fang",'+
'"https://github.com/rajanil",'+
'"https://github.com/rajido",'+
'"https://github.com/randommm",'+
'"https://github.com/ranveeraggarwal",'+
'"https://github.com/raphael-ritz",'+
'"https://github.com/raphg",'+
'"https://github.com/raquele",'+
'"https://github.com/ratsch",'+
'"https://github.com/rawatarun",'+
'"https://github.com/rbakker",'+
'"https://github.com/rcannood",'+
'"https://github.com/rcavalcante",'+
'"https://github.com/rcurrie",'+
'"https://github.com/rdejonge",'+
'"https://github.com/rdiaz02",'+
'"https://github.com/reece",'+
'"https://github.com/remimarenco",'+
'"https://github.com/rfdougherty",'+
'"https://github.com/rhallPB",'+
'"https://github.com/rhastings",'+
'"https://github.com/rhodricusack",'+
'"https://github.com/rhr",'+
'"https://github.com/ric70x7",'+
'"https://github.com/rich-iannone",'+
'"https://github.com/rich7409",'+
'"https://github.com/richardmleggett",'+
'"https://github.com/richardxia",'+
'"https://github.com/rishidev",'+
'"https://github.com/rjleveque",'+
'"https://github.com/rkacker",'+
'"https://github.com/rkitchen",'+
'"https://github.com/rlaverde",'+
'"https://github.com/rleonid",'+
'"https://github.com/rlgoldfeder",'+
'"https://github.com/rmcclosk",'+
'"https://github.com/rmcelreath",'+
'"https://github.com/rmcgibbo",'+
'"https://github.com/robertoostenveld",'+
'"https://github.com/roblanf",'+
'"https://github.com/rohanmaddamsetti",'+
'"https://github.com/rossant",'+
'"https://github.com/rpique",'+
'"https://github.com/rproepp",'+
'"https://github.com/rr1859",'+
'"https://github.com/rrwick",'+
'"https://github.com/rsalek",'+
'"https://github.com/rsbaucom",'+
'"https://github.com/rtabbara",'+
'"https://github.com/rtobes",'+
'"https://github.com/ruanjue",'+
'"https://github.com/rudibroekhuizen",'+
'"https://github.com/ruolin",'+
'"https://github.com/russcd",'+
'"https://github.com/rvaser",'+
'"https://github.com/rvosa",'+
'"https://github.com/ryan-williams",'+
'"https://github.com/ryanlayer",'+
'"https://github.com/ryscher",'+
'"https://github.com/rzelayafavila",'+
'"https://github.com/saemi",'+
'"https://github.com/saezrodriguez",'+
'"https://github.com/sahilseth",'+
'"https://github.com/sahrendt0",'+
'"https://github.com/sandipchatterjee",'+
'"https://github.com/sandywang",'+
'"https://github.com/sarahbuzz",'+
'"https://github.com/sarahhunt",'+
'"https://github.com/sarahmid",'+
'"https://github.com/sarbal",'+
'"https://github.com/sarisbro",'+
'"https://github.com/satoken",'+
'"https://github.com/satra",'+
'"https://github.com/sbenz",'+
'"https://github.com/scanon",'+
'"https://github.com/schlegelp",'+
'"https://github.com/schoffelen",'+
'"https://github.com/sdumitriu",'+
'"https://github.com/sebastian-luna-valero",'+
'"https://github.com/sebastianduchene",'+
'"https://github.com/secastel",'+
'"https://github.com/seth-ament",'+
'"https://github.com/sggaffney",'+
'"https://github.com/shahmoradi",'+
'"https://github.com/shahpr",'+
'"https://github.com/shajoezhu",'+
'"https://github.com/sharpton",'+
'"https://github.com/shaunmahony",'+
'"https://github.com/shaw2thefloor",'+
'"https://github.com/shesketh",'+
'"https://github.com/shiltemann",'+
'"https://github.com/shntnu",'+
'"https://github.com/simleo",'+
'"https://github.com/simongog",'+
'"https://github.com/simonvh",'+
'"https://github.com/sinanugur",'+
'"https://github.com/sisch",'+
'"https://github.com/sjbeckett",'+
'"https://github.com/sjczheng",'+
'"https://github.com/sjspielman",'+
'"https://github.com/skeenan",'+
'"https://github.com/skoren",'+
'"https://github.com/skumagai",'+
'"https://github.com/slarson",'+
'"https://github.com/slisovski",'+
'"https://github.com/smangul1",'+
'"https://github.com/smhoban",'+
'"https://github.com/smithmj",'+
'"https://github.com/smondet",'+
'"https://github.com/smorfopoulou",'+
'"https://github.com/snacktavish",'+
'"https://github.com/snayfach",'+
'"https://github.com/sneakerkg",'+
'"https://github.com/snsansom",'+
'"https://github.com/soccin",'+
'"https://github.com/sofroniewn",'+
'"https://github.com/songgang",'+
'"https://github.com/sophie63",'+
'"https://github.com/spacocha",'+
'"https://github.com/spradervand",'+
'"https://github.com/spulido99",'+
'"https://github.com/spyysalo",'+
'"https://github.com/sri2k1us",'+
'"https://github.com/srobb1",'+
'"https://github.com/srutschmann",'+
'"https://github.com/srynobio",'+
'"https://github.com/sschmeier",'+
'"https://github.com/sseemayer",'+
'"https://github.com/sstevens2",'+
'"https://github.com/stain",'+
'"https://github.com/stamatak",'+
'"https://github.com/stebjan",'+
'"https://github.com/steffejr",'+
'"https://github.com/stephaneguindon",'+
'"https://github.com/stephaniehicks",'+
'"https://github.com/stephenfloor",'+
'"https://github.com/stephens999",'+
'"https://github.com/stephenturner",'+
'"https://github.com/steve-gregory",'+
'"https://github.com/steveherrin",'+
'"https://github.com/stevekm",'+
'"https://github.com/stevemock",'+
'"https://github.com/steven-albanese",'+
'"https://github.com/stevenwilder",'+
'"https://github.com/stnava",'+
'"https://github.com/strootman",'+
'"https://github.com/stschiff",'+
'"https://github.com/stuartmac",'+
'"https://github.com/surchs",'+
'"https://github.com/susannvorberg",'+
'"https://github.com/susjoh",'+
'"https://github.com/svendaehne",'+
'"https://github.com/svituz",'+
'"https://github.com/svkazakov",'+
'"https://github.com/swederik",'+
'"https://github.com/sxjscience",'+
'"https://github.com/syclik",'+
'"https://github.com/szitenberg",'+
'"https://github.com/szpiech",'+
'"https://github.com/tanghaibao",'+
'"https://github.com/taoliu",'+
'"https://github.com/tare",'+
'"https://github.com/tarunaaggarwal",'+
'"https://github.com/tavinathanson",'+
'"https://github.com/tbrittoborges",'+
'"https://github.com/tderrien",'+
'"https://github.com/tdreszer",'+
'"https://github.com/tedgin",'+
'"https://github.com/telenius",'+
'"https://github.com/terrytangyuan",'+
'"https://github.com/tetron",'+
'"https://github.com/tfenne",'+
'"https://github.com/tgouhier",'+
'"https://github.com/theis188",'+
'"https://github.com/thermokarst",'+
'"https://github.com/thh32",'+
'"https://github.com/thibauthourlier",'+
'"https://github.com/thierrygosselin",'+
'"https://github.com/thijsdhollander",'+
'"https://github.com/thirdwing",'+
'"https://github.com/thk2008",'+
'"https://github.com/thomasmaurel",'+
'"https://github.com/thomasoniii",'+
'"https://github.com/thouis",'+
'"https://github.com/timodonnell",'+
'"https://github.com/tj8901nm",'+
'"https://github.com/tknijnen",'+
'"https://github.com/tkuhn",'+
'"https://github.com/tmooney",'+
'"https://github.com/tombergk",'+
'"https://github.com/tomgilissen",'+
'"https://github.com/torognes",'+
'"https://github.com/tqchen",'+
'"https://github.com/tracysmith",'+
'"https://github.com/transcript",'+
'"https://github.com/trayc7",'+
'"https://github.com/treangen",'+
'"https://github.com/trgao10",'+
'"https://github.com/tritemio",'+
'"https://github.com/trondik",'+
'"https://github.com/trvrb",'+
'"https://github.com/tsackton",'+
'"https://github.com/tseemann",'+
'"https://github.com/tshmak",'+
'"https://github.com/tsirigos",'+
'"https://github.com/tslumley",'+
'"https://github.com/ttesileanu",'+
'"https://github.com/ttriche",'+
'"https://github.com/twestbrookunh",'+
'"https://github.com/tyleramos",'+
'"https://github.com/tylerhether",'+
'"https://github.com/ueser",'+
'"https://github.com/ulyantsev",'+
'"https://github.com/umutcaglar",'+
'"https://github.com/unidesigner",'+
'"https://github.com/uqrmaie1",'+
'"https://github.com/uriba",'+
'"https://github.com/variani",'+
'"https://github.com/varnerlab",'+
'"https://github.com/vipints",'+
'"https://github.com/vivekiitkgp",'+
'"https://github.com/vladsaveliev",'+
'"https://github.com/vqv",'+
'"https://github.com/vsp-jenkins-bot",'+
'"https://github.com/vtlim",'+
'"https://github.com/vyahhi",'+
'"https://github.com/wacguy",'+
'"https://github.com/walkergussler",'+
'"https://github.com/wanfahmi",'+
'"https://github.com/weikanggong",'+
'"https://github.com/wellecks",'+
'"https://github.com/wenjiegroup",'+
'"https://github.com/wgar84",'+
'"https://github.com/whao89",'+
'"https://github.com/wholeslide",'+
'"https://github.com/wiheto",'+
'"https://github.com/wikiselev",'+
'"https://github.com/willmclaren",'+
'"https://github.com/wjrl",'+
'"https://github.com/wjurkowski",'+
'"https://github.com/x0xMaximus",'+
'"https://github.com/x4nd3r",'+
'"https://github.com/xapple",'+
'"https://github.com/xavierdidelot",'+
'"https://github.com/xbian",'+
'"https://github.com/xiangfstats",'+
'"https://github.com/xiaochuanle",'+
'"https://github.com/xjwanglab",'+
'"https://github.com/xqwen",'+
'"https://github.com/xuebingwu",'+
'"https://github.com/xypan1232",'+
'"https://github.com/yangao07",'+
'"https://github.com/yangzhi-psy",'+
'"https://github.com/yanqingmen",'+
'"https://github.com/yarikoptic",'+
'"https://github.com/yhoogstrate",'+
'"https://github.com/yifeng-li",'+
'"https://github.com/yil8",'+
'"https://github.com/yiminghu",'+
'"https://github.com/yjingj",'+
'"https://github.com/ymatts",'+
'"https://github.com/yoheirosen",'+
'"https://github.com/ypriverol",'+
'"https://github.com/yuanfenw",'+
'"https://github.com/yuelab",'+
'"https://github.com/z0on",'+
'"https://github.com/zdealveindy",'+
'"https://github.com/zeux",'+
'"https://github.com/zhandong",'+
'"https://github.com/zhangsaithu",'+
'"https://github.com/zhenwendai",'+
'"https://github.com/zhouxiaofan1983",'+
'"https://github.com/zkamvar",'+
'"https://github.com/zlskidmore",'+
'"https://github.com/zmz2",'+
'"https://github.com/zorgiepoo",'+
'"https://github.com/zuoxinian",'+
'"https://github.com/zyndagj"]}';

var users = JSON.parse(text);
var starred = require('../lib/switcher');

for(i=0; i<users.biouser.length; i++){
	username = users.biouser[i].replace("https://github.com/","");
	
	starred("stars/".concat(username),function(err,data){
		if(data.entries.length !== 'undefined'){
			for(j=0; j<data.entries.length; j++){
				process.stdout.write(data.url.replace("https://github.com/stars/","")+"\t");
				process.stdout.write(data.entries[j]+"\t");
				process.stdout.write("\n");
			}
		}
		if(typeof data.next_page !== 'undefined'){
			starred(data.next_page,function(err,data2){
				for(k=0; k<data2.entries.length; k++){
					process.stdout.write(data.url.replace("https://github.com/stars/","")+"\t");
					process.stdout.write(data2.entries[k]+"\t");
					process.stdout.write("\n");
				}
				
				if(typeof data2.next_page !== 'undefined'){
					starred(data2.next_page,function(err,data3){
						for(l=0; l<data3.entries.length; l++){
							process.stdout.write(data.url.replace("https://github.com/stars/","")+"\t");
							process.stdout.write(data3.entries[l]+"\t");
							process.stdout.write("\n");
						}
						
						if(typeof data3.next_page !== 'undefined'){
							starred(data3.next_page,function(err,data4){
								for(l=0; l<data4.entries.length; l++){
									process.stdout.write(data.url.replace("https://github.com/stars/","")+"\t");
									process.stdout.write(data4.entries[l]+"\t");
									process.stdout.write("\n");
								}
						
							})
						
						}
						
					})
						
				}
			
			
			
			
			})
		}
		
	})
	
	
}



