var text = '{"repos" :'+
'["/10XGenomics",'+
'"/21zhangqiong/MEG_Alignment",'+
'"/23andMe/yhaplo",'+
'"/4ment",'+
'"/4ureliek/ReannTE",'+
'"/aalto-icskepaco",'+
'"/abehr/pong",'+
'"/ablab/mgra/",'+
'"/abramovitchMSU/",'+
'"/abrown25/qvalue",'+
'"/ackman678/wholeBrainDX",'+
'"/ad3002/Cookiecutter",'+
'"/adamallo/SimPhy",'+
'"/adamewing/bamsurgeon",'+
'"/adaptivegenome/clusterseq",'+
'"/AdelaideBioinfo",'+
'"/AdelaideBioinfo/retrotransposonAccumulation",'+
'"/adrinjalali/Network-Classifier",'+
'"/adsteen/enzalyze",'+
'"/AgResearch/KGD.git",'+
'"/ahwillia/Williams-etal-Synaptic-Transport340",'+
'"/aivelo/lemur-community",'+
'"/alanzos/ExInAtor/",'+
'"/AlastairKerr/Robson2016",'+
'"/alcideschaux/Penis-p53",'+
'"/aldro61/kover/",'+
'"/alegarra/metafounders",'+
'"/alexcritschristoph/CircMG",'+
'"/alexdobin/STAR/blob/master/doc/STARmanual",'+
'"/alexviiia/dpuc2",'+
'"/ali-cp/QASDRA.git",'+
'"/alizrrao/DepthOfCoveragePerInterval",'+
'"/AllonKleinLab/SPRING/",'+
'"/almlab/SmileTrain/wiki/",'+
'"/almlab/sycamore",'+
'"/alyssafrazee/ballgown_code",'+
'"/alyssafrazee/polyester",'+
'"/amirrezaw/automagic",'+
'"/amkozlov/sativa",'+
'"/ammodramus/coalseam",'+
'"/AnaPoets/BarleyLandraces",'+
'"/andreagobbi/pyBiRewire",'+
'"/andreas-schlicker/OncoScape",'+
'"/andrewdhawan/alkcollateral-sensitivity",'+
'"/andrewjpage",'+
'"/andyljones/NeuralNetworkMicroarraySegmentation",'+
'"/ansariazim/TreeBreaker",'+
'"/apuapaquola/rf.git",'+
'"/araksm/ceRNA/",'+
'"/ariutta/svg-pan-zoom",'+
'"/arlin/PenG_and_GLin",'+
'"/arokem/att_ss",'+
'"/arq5x/bedtools",'+
'"/arq5x/bedtools2/releases",'+
'"/arq5x/nanopore-scripts",'+
'"/arq5x/nanopore-scripts",'+
'"/arq5x/poretools",'+
'"/arq5x/poretools",'+
'"/ARTbio/tools­artbio/",'+
'"/ArtRand/signalAlign",'+
'"/ArunasRadzvilavicius/GermlineEvolution",'+
'"/aryeelab/diffloop_paper/",'+
'"/ashutoshkpandey/Variants_call/blob/master/Filter_GATK_vcf.py",'+
'"/asifrim/mrmosaic",'+
'"/asncd/schimera",'+
'"/a-teufel/Accelerated_Sim",'+
'"/atifrahman/SWALO/tree/scripts",'+
'"/atredennick/Coexistence-Stability",'+
'"/atredennick/MicroMesoForecast/releases",'+
'"/au-bios/python-landscapegen",'+
'"/ausmeyer/pneumococcal_173",'+
'"/azizka/Speciesgeocoder-Rpackage",'+
'"/babelomics/hipathia",'+
'"/baharpan/cosmo/tree/positional",'+
'"/bahlolab/isoRelate",'+
'"/baillielab/coexpression/",'+
'"/balaur",'+
'"/balicea/RNA-discrete-dynamical-modeling",'+
'"/barricklab/breseq",'+
'"/bartongroup/AlmostSignificant",'+
'"/bbimber/discvr-seq/",'+
'"/bbitarello",'+
'"/bcgsc/abyss/tree/",'+
'"/BD2K-DDI",'+
'"/BEAST2-Dev/bModelTest",'+
'"/beecycles/Bees-without-flowers-432",'+
'"/behrimg/Scripts/blob/master/Hall_Projects/Pombe/MA_Pipeline.txt",'+
'"/benaug/SCRRcpp",'+
'"/benfulcher/",'+
'"/benfulcher/hctsa",'+
'"/benjaminhgood/mutator_simulations",'+
'"/benjjneb/dada2",'+
'"/bensassonlab/scripts",'+
'"/bensassonlab/yeastecology/",'+
'"/bensutherland/salp_anon_to_sfon",'+
'"/benwilson87/evolutionary-rescue-soft-sweeps",'+
'"/bergeycm/",'+
'"/bergmanlab/mcclintock",'+
'"/bhaibeka/PharmacoGx> ",'+
'"/bhklab/cdrug/blob/",'+
'"/bhklab/DNF",'+
'"/bhklab/DrugTissue",'+
'"/bhklab/EpiStroma-webapp",'+
'"/bhklab/MetaGxData",'+
'"/BigNeuron/BigNeuron-Wiki/wiki/Neuron-Reconstruction-Algorithms",'+
'"/bihealth/hlama",'+
'"/BilkentCompGen/dipseq",'+
'"/BIMIB-DISCo/TRONCO.Contact",'+
'"/binarybottle/roygbiv",'+
'"/binaypanda/RNAtor",'+
'"/BinPro/CONCOCT",'+
'"/biocaddie/WG3",'+
'"/biocore/",'+
'"/BioDepot",'+
'"/BioDepot/BioDepot-workflow-builder",'+
'"/biofilos/cgp_finder",'+
'"/bioinfologics/",'+
'"/bioinfonm/microBat",'+
'"/bioinformatics-centre/kaiju",'+
'"/bioinfo-ut/GenomeTester4/",'+
'"/BiologicalRecordsCentre/RangeChangeSims",'+
'"/biometry/EvidenceAssessmentTool/blob/master/Examples.xlsx",'+
'"/biorack",'+
'"/bjornwallner/proteus",'+
'"/blachlylab",'+
'"/Blahah/transrate",'+
'"/blasseigne/ProliferativeIndex",'+
'"/blekhmanlab/hominid",'+
'"/bmbolstad/affyio",'+
'"/bmbolstad/preprocessCore",'+
'"/bmvdgeijn/WASP/",'+
'"/bneron",'+
'"/Bohdan-Khomtchouk/ENCODE_TF_geneXtendeR_analysis",'+
'"/Bohdan-Khomtchouk/Microscope",'+
'"/Bohdan-Khomtchouk/shinyheatmap",'+
'"/bomeara/phrapl",'+
'"/bondlab/scripts",'+
'"/boopsboops/primates-genome-phylo",'+
'"/bpbond",'+
'"/bradleylab/DsrAB_enzyme_models",'+
'"/brandonlind/whitebark_pine",'+
'"/Brazelton-Lab",'+
'"/brentp",'+
'"/brentp/peddyDemonstration",'+
'"/brielin/",'+
'"/brielin/popcorn",'+
'"/broadinstitute/hail",'+
'"/bsipos/paper-pasp",'+
'"/bulik/ldsc",'+
'"/bulik/ldsc;",'+
'"/bulik/ldsc/",'+
'"/bulik/ldsc/",'+
'"/bulik/ldsc",'+
'"/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial",'+
'"/bxlab/hifive",'+
'"/Caetanods/Dipsadidae_color_evolution",'+
'"/Caged/d3-tip",'+
'"/CaioFreire/CUB",'+
'"/camillescott/dammit;",'+
'"/CampagneLaboratory/goby3",'+
'"/CampagneLaboratory/gobyweb2-plugins/tree/127",'+
'"/CampagneLaboratory/variationanalysis",'+
'"/cancergenetics/cancergd",'+
'"/cangermueller/deepcpg",'+
'"/canlab/MediationToolbox",'+
'"/canlab/RobustToolbox",'+
'"/carolinecolijn/treetop",'+
'"/carpenterlab/2016_pawlowski_mlcb",'+
'"/carpenterlab/2016_rohban_submitted ",'+
'"/carrillo",'+
'"/carringtonlab/TargetFinder",'+
'"/cashalow/teleost-radiation",'+
'"/cashoes/enumerateblood",'+
'"/catavallejos/BASiCS;",'+
'"/catavallejos/BASiCS",'+
'"/catmaid/CATMAID",'+
'"/cbahlai/lampyrid/",'+
'"/cbg-ethz/5-virusmix",'+
'"/cbg-ethz/SCITE",'+
'"/cBioLab/sWM",'+
'"/cboettig/appl",'+
'"/cbrueffer",'+
'"/ccraddock/afni",'+
'"/ccshao/maIHB",'+
'"/cdcepi/",'+
'"/CellProfiler/CellProfiler-Analyst",'+
'"/CellProfiler/CellProfiler/wiki/Adapting-CellProfiler-to-a-LIMS-environment",'+
'"/cfriedline/foxtail_linkage.525",'+
'"/cfriedline/foxtail_wue",'+
'"/CGATOxford/UMI-tools",'+
'"/cggh/panoptes",'+
'"/CGRL-QB3-UCBerkeley/denovoTargetCapturePopGen",'+
'"/cgwyx/debian_prokka_panx_antismash_docker",'+
'"/champost/ABLE",'+
'"/chapmanb/bcbio-nextgen",'+
'"/chedonat/OncoPhase",'+
'"/chiasto/hyRAD",'+
'"/chiulab/MetaPORE",'+
'"/chiulab/surpi",'+
'"/choderalab/132",'+
'"/choderalab/dispensing-errors-manuscript",'+
'"/choderalab/ensembler",'+
'"/choderalab/itc-worksheet",'+
'"/chr1swallace/cd4-pchic/blob/master/make_modules.R",'+
'"/chr1swallace/GUESSFM",'+
'"/chr1swallace/TibsPower",'+
'"/Chris1221/goldi",'+
'"/chrisamiller/fishplot",'+
'"/ChrisHIV/shiver",'+
'"/chrisquince/DESMAN",'+
'"/ChristopherWilks/snaptron",'+
'"/chuckpr/BvP_manuscript_figures.199",'+
'"/chuckpr/CSIP_succession_",'+
'"/chuckpr/NSIP_data_analysis254",'+
'"/churchill-433",'+
'"/churchill-lab/gbrs",'+
'"/churchlab/optmage",'+
'"/cianodonnell/PopulationTracking",'+
'"/Cibiv/Teaser",'+
'"/cidvbi/PathogenPortal",'+
'"/ciiram/",'+
'"/ckinzthompson/biasd",'+
'"/clawpack/riemann",'+
'"/clemlab/ml-3",'+
'"/cmagnabosco/OmicPipelines",'+
'"/CMPG/ADMRE",'+
'"/cmu-phil/tetrad",'+
'"/CNSGenomics/impute-pipe",'+
'"/CobraLab/MAGeTbrain",'+
'"/ColeLab/",'+
'"/colomoto/logicalmodel",'+
'"/COMBINE-lab/matryoshka",'+
'"/COMBINE-lab/maximumlikelihood-relatedness-estimation",'+
'"/COMBINE-lab/quark",'+
'"/common-workflow-language/common-workflow-language",'+
'"/conscho/phylo",'+
'"/coreymhudson/AffyDistance",'+
'"/cortex-lab/Suite2P",'+
'"/cotsapaslab/",'+
'"/counsyl/hgvs",'+
'"/counsyl/sscm",'+
'"/crs4/pyEHR",'+
'"/crs4/rapi",'+
'"/crukci-bioinformatics/camcAPP",'+
'"/ctb/",'+
'"/ctlab/fgsea",'+
'"/CuppenResearch/MutationalPatterns",'+
'"/cutterlab",'+
'"/cuttlefishh/papers",'+
'"/D",'+
'"/dad/mrna-prot",'+
'"/DanChitwood/PassifloraLeaves",'+
'"/danielriosgarza/Bottom_Up_Ecology_Functions",'+
'"/danilinares/2016LinaresLopezmoliner",'+
'"/danimag/tkrelated",'+
'"/Danko-Lab/rtfbs_db",'+
'"/danlwarren/RWTY",'+
'"/datajoint/datajoint-matlab",'+
'"/davek44/Basset",'+
'"/david940408/CAMer",'+
'"/david940408/CAMer",'+
'"/davidaknowles/eagle",'+
'"/davidaknowles/leafcutter",'+
'"/davidmam/DMAP.git",'+
'"/davidrasm/PairTree",'+
'"/dcjones/isolator",'+
'"/ddarriba/partitiontest",'+
'"/ddofer/asap",'+
'"/debbiemarkslab/plmc",'+
'"/de-Bivort-",'+
'"/deboraycb/reliability_hla_1000g",'+
'"/DecodeGenetics/BamHashContact",'+
'"/DecodeGenetics/chopBAI",'+
'"/dekkerlab/cworld‐",'+
'"/dereneaton/virentes",'+
'"/DeveauP/QuantumClone/",'+
'"/devillemereuil/qgglmm.96",'+
'"/devosoft/avida",'+
'"/deweylab/metasra-pipeline",'+
'"/dfporter",'+
'"/dg13/rasqual/",'+
'"/dhimmel/hetio",'+
'"/dhkron/PSYCHIC",'+
'"/DiegoCambuy/CAT",'+
'"/dimenwarper/gett",'+
'"/dipetkov/eems",'+
'"/diriano/ploidyNGS",'+
'"/distancedevelopment/readdst",'+
'"/dkoslicki/EMDeBruijn",'+
'"/dkoslicki/EMDeBruijn",'+
'"/dkoslicki/MetaPalettePre-trained",'+
'"/DL42/GOFish",'+
'"/dlampart/csrproject",'+
'"/dluntzer/",'+
'"/dmlc/mxnet",'+
'"/dnaase/Bistools/tree/master/for_recomb2015Paper",'+
'"/DNAworker/DNAlogo",'+
'"/dohalloran/phylo-node",'+
'"/donkeyshot/phybreak",'+
'"/doricke/Divergence",'+
'"/doricke/IBio",'+
'"/douglasgscofield/add-to-Qiime-DB",'+
'"/dpryan79/PileOMeth",'+
'"/DRL/blobtools/blob/master/README.md",'+
'"/drmaa-python",'+
'"/dsjohnson/multAbund",'+
'"/dspeyer/ubiq_genome",'+
'"/dufourya/SwimTracker",'+
'"/dwinter/accumulate;",'+
'"/DworkinLab/TestaDworkin2016DGE",'+
'"/EarnshawLab/nanoRF",'+
'"/ebov/space-time",'+
'"/eduati/BraDiPluS",'+
'"/egeeamu/voskhod",'+
'"/eiriniar/CellCnn",'+
'"/ekg/freebayes",'+
'"/ekg/glia",'+
'"/eliotmiller/metricTester",'+
'"/elzbth/ChromoViz",'+
'"/emjosephs/eQTL",'+
'"/emreg00/proxide",'+
'"/ENCODE-DCC/kentUtils/blob/v302.1.0/bin/",'+
'"/ENCODE-DCC/snovault/",'+
'"/enormandeau/mapcomp/",'+
'"/enormandeau/mapcomp/",'+
'"/Ensembl",'+
'"/ensembl-variation/VEP_plugins",'+
'"/EnvGen/Tutorials",'+
'"/epierson9/",'+
'"/EpiStemNet",'+
'"/episurg/episurg",'+
'"/ericschulz/contextualbandits",'+
'"/eriqande/gaiah",'+
'"/eriqande/wiwa-popgen",'+
'"/erscott/RASLseqTools",'+
'"/esbeneickhardt/TFBSAnnotator",'+
'"/etal",'+
'"/Ettwiller/Damage­estimator",'+
'"/Ettwiller/TSS/",'+
'"/evocellnet/ksea",'+
'"/evogytis/MERS",'+
'"/evolscientist/ExpressionHMM.git.474",'+
'"/faircloth-202",'+
'"/faircloth-­lab/phyluce/",'+
'"/faircloth-lab/phyluce/",'+
'"/faircloth-lab/radcap",'+
'"/fairmiracle/AMOUNTAIN",'+
'"/famulare/howPolioVaccinationAffectsPoliovirusTransmission",'+
'"/faraway1nspace",'+
'"/FaustFrankenstein/RandomForestFramework/releases/tag/v1.0",'+
'"/fbreitwieser/pavian",'+
'"/fchollet/keras",'+
'"/Fei-Lu/FastCall",'+
'"/fengzhanglab",'+
'"/ferracimo",'+
'"/fgvieira/ngsF",'+
'"/finkelsteinlab/fylm",'+
'"/fjhheras/phhotoreceptor",'+
'"/fjug/MoMA/wiki/MoMA%20Movies",'+
'"/flass/agrogenom",'+
'"/fliem/LIFE_RS_preprocessing",'+
'"/footprint",'+
'"/FrancescaMancini/Flickr-API",'+
'"/francescojm/SLAPenrich",'+
'"/FrankD/fuser",'+
'"/fraser-lab/EMRinger",'+
'"/fraser-lab/PUBS2014",'+
'"/FRED-2/OptiType",'+
'"/friend1ws",'+
'"/fritzsedlazeck/",'+
'"/fritzsedlazeck/SURVIVOR",'+
'"/fstrozzi",'+
'"/fukunagatsu/RIblast",'+
'"/funkhou9/edit",'+
'"/funpopgen/CaVEMaN.298",'+
'"/fuopen/3",'+
'"/fusaroli/AcousticPatternsInASD",'+
'"/fvandin/ExaLT",'+
'"/fxia22/HINGE",'+
'"/ga4gh/benchmarking-tools/blob/master/resources/",'+
'"/ga4gh/schemas",'+
'"/ga4gh/schemas/wiki/Human-Genome-Variation-Map-(HGVM",'+
'"/gabraham/flashpca",'+
'"/galaxyproject/",'+
'"/Gammerdinger/sex-­‐SNP-­‐finder",'+
'"/gangwug/MetaCycle",'+
'"/gaoshanT/Fastq_clean",'+
'"/gauravbhatia1/PCGCRegression",'+
'"/gbradburd/SpaceMix",'+
'"/gc5k/GEAR/wiki/EigenGWAS",'+
'"/gdevailly",'+
'"/gem-480",'+
'"/Generade-nl/TULIP",'+
'"/geneva/POPBAMTools",'+
'"/genome/bam-readcount",'+
'"/genome/bamreadcount",'+
'"/genomecuration/JAMg",'+
'"/genome-in-a-bottle",'+
'"/genome-in-a-bottle/giab",'+
'"/GenomicsCoreLeuven/GBSX",'+
'"/genoo/GenOO",'+
'"/georgebusby/popgen",'+
'"/GeorgievLab/CeCe/",'+
'"/germs-152",'+
'"/gersteinlab/HiC_spector",'+
'"/gersteinlab/MrTADFinder",'+
'"/GGiecold",'+
'"/Gibbsdavidl/miergolf",'+
'"/gigascience/paper-zhang2014/tree/master/Genome_assembly/SOAPdenovo",'+
'"/GiliG/NetStruct",'+
'"/gilles-didier/",'+
'"/gilles-didier/TDALP",'+
'"/giorap/tv-plots",'+
'"/giraola/KARL",'+
'"/gireeshkbogu/chromatin_state",'+
'"/gmarcais/Jellyfish/releases",'+
'"/gmiaslab/mathiomica",'+
'"/GNilsonne/IL6_diurnal",'+
'"/G-Node/nix/wiki.681",'+
'"/goeckslab/isoseq-browser",'+
'"/govinda-kamath/clustering",'+
'"/gpu-pdl-nudt/GeRelion",'+
'"/GreallyLab/Nadel-et-al.-2015",'+
'"/greenelab/adage",'+
'"/greenelab/continuous_analysis",'+
'"/greenelab/DAPS",'+
'"/greenelab/nf1_inactivation",'+
'"/greenelab/tad_pathways",'+
'"/GreenleafLab/NucleoATAC",'+
'"/Gregor-Mendel-Institute/atpolydb.421",'+
'"/Gregor-­‐Mendel-­‐Institute/swedish-­‐genomes",'+
'"/griffithlab/GenVisR/issues",'+
'"/grocsvs/grocsvs",'+
'"/grunwaldlab/metacoder",'+
'"/guigolab/CRISPETA",'+
'"/ha0ye/rEDM",'+
'"/hacone/AgIn",'+
'"/hagenaue/BrainInABlender",'+
'"/hailianghuang/efficientPCA",'+
'"/hakyimlab/MetaXcan",'+
'"/hakyimlab/PrediXcan",'+
'"/hall-lab/svtyper",'+
'"/hammerlab/paperaocs-chemo-neoantigens",'+
'"/hammerlab/pileup.js",'+
'"/hammerlab/topeology",'+
'"/hansenlab/EPIC450k",'+
'"/harry­thorpe/Intergenic_selection_paper; full instructions available",'+
'"/HarvardForest/SarrSens.207",'+
'"/hclimente/smartas",'+
'"/hdetering/discomark",'+
'"/health1987/dist",'+
'"/hechao0407/HBP/blob/master/HBP_1.0.tar.gz",'+
'"/hemberg-lab/D3E",'+
'"/hesselberthlab/modmap",'+
'"/hewittlab/Crossbow-GCE-Hadoop",'+
'"/HGID/WES_vs_WGS",'+
'"/HioBeen",'+
'"/hitbc/deSPI",'+
'"/hly89/FIMMCherry",'+
'"/hmatsu1226/SCODE",'+
'"/hmorlon/PANDA",'+
'"/holtjma/msbwt/wiki/Converting-to-msbwt’s-RLE-format",'+
'"/homopolymer/PyroTools",'+
'"/HongjianLi/idock",'+
'"/HudsonAlpha/aRNAPipe",'+
'"/huizhangucas/CISD",'+
'"/HullUni-bioinformatics/Diplotaxodon_twilight_RAD;",'+
'"/HullUni-bioinformatics/metaBEAT",'+
'"/huwenboshi/ImpG",'+
'"/hzi-bifo/traitar",'+
'"/i5K",'+
'"/iamciera/sister-of-pin1-material",'+
'"/ibartomeus/cdddca21d5dbff26a25e",'+
'"/ibartomeus/powerlines",'+
'"/ibartomeus/RE_traits",'+
'"/ibest/ARC",'+
'"/ICBI/viGEN/",'+
'"/ICONIC-UCL/vir-flow",'+
'"/identifiers-org/prefix/blob/master/prefix.yaml",'+
'"/idrnotebooks",'+
'"/ihh/dart/tree/master/src/tkf",'+
'"/ihh/dnastore",'+
'"/ihh/indelhistorian",'+
'"/ikwak2/funqtl",'+
'"/Illumina/canvas",'+
'"/Illumina/ExpansionHunter",'+
'"/Illumina/manta",'+
'"/Illumina/pyflow",'+
'"/Illumina/tHapMix",'+
'"/IlyaLab/CombiningDependentPvaluesUsingEBM",'+
'"/INCF/openfmri2bids",'+
'"/InesdeSantiago/BaalChIP769",'+
'"/InouyeLab/NetRep",'+
'"/institut-de-genomique/MaGuS",'+
'"/interCM/evolution",'+
'"/iontorrent/TS/tree/master/Analysis/TMAP",'+
'"/iosonofabio",'+
'"/iPlantCollaborativeOpenSource/iplant-agave-sdk",'+
'"/ipw012/RIVER",'+
'"/iqbal-lab/cortex",'+
'"/iqbal-lab/gramtools",'+
'"/iqballab/Mykrobe-predictor",'+
'"/ISA-tools/NanoMaton",'+
'"/isb-cgc/ISBCGC-pipelines",'+
'"/isovic/graphmap",'+
'"/isovic/racon.git",'+
'"/itseez/opencv",'+
'"/ivazquez/gv-paper-2016",'+
'"/jackhump",'+
'"/jacobian1980/pfmix",'+
'"/jade-cheng/ohana",'+
'"/jakejh/zeitzeiger. All data and code ",'+
'"/jamescrall/BEEtag",'+
'"/jamesliley/subtest",'+
'"/jameslyons/python_speech_features",'+
'"/jasonsahl/UGAP",'+
'"/jasperlinthorst/REVEAL",'+
'"/jbkinney/",'+
'"/jbkinney/sortseq",'+
'"/jbloom/",'+
'"/jbloomlab/reedmuenchcalculator",'+
'"/jbyoder/mutualism-sanctions-recognition",'+
'"/jcarrotzhang/LoLoPicker",'+
'"/j-chou/SVDquartets.git",'+
'"/jdherman/salib",'+
'"/jdiedrichsen/pcm_toolbox",'+
'"/jdjgilbert/thrips.git",'+
'"/jdstorey/qvalue",'+
'"/jdstorey/qvalue",'+
'"/jdtournier/mrtrix3",'+
'"/JDureau/ssm/blob/master/doc/665",'+
'"/jedick/canprot",'+
'"/jeetsukumaran/archipelago",'+
'"/jeffreyvarner/TGFb-VEGFA-Model",'+
'"/jeparson/mixtureprocesscontrol",'+
'"/JeremyHorst/MinorityReport",'+
'"/jeremymcrae/denovoFilter",'+
'"/jeromekelleher/msprime-paper",'+
'"/Jfortin1/HiC_AB_Compartments",'+
'"/jgurtowski/nanocorr",'+
'"/jhawkey/IS_mapper",'+
'"/jhcepas/emapper-benchmark",'+
'"/JiangTian/adaptive-",'+
'"/jijiadong/JDINAC",'+
'"/jimhester/knitrBootstrap",'+
'"/jimhester/knitrBootstrap",'+
'"/jimhester/primerTree",'+
'"/jkenney9a/Zebrafish",'+
'"/jlleslie/Intraspecific_Competition/blob/master/methods/Verocell_Toxin501",'+
'"/jmacdona/B_megaterium_modelling",'+
'"/joebathelt/ZDHHC9_connectome",'+
'"/joelhsmth/startmrca",'+
'"/joepickrell/",'+
'"/joepickrell/1000-genomes",'+
'"/joewandy/HDP-Align",'+
'"/JohnEPool/SIBSAM1",'+
'"/johnomics",'+
'"/JohnReid/DeLorean/",'+
'"/jonchang/eol-mturk-landmark.86",'+
'"/jorruior/CIPHER",'+
'"/josephryan/reduce_refseq",'+
'"/josephryan/RyanLab/tree/master/2015Zwarycz_et_al",'+
'"/josephryan/sowhat/commit/e0c214e8d",'+
'"/josephwb/tu",'+
'"/joshuabhk/methylsuite",'+
'"/jotwin/coevolution",'+
'"/JovMaksimovic/methyl-seq_bpipe",'+
'"/jpritt/boiler",'+
'"/jsharbrough/grabContigs",'+
'"/jsilve24/philr",'+
'"/jstapleton/synthetic_reads",'+
'"/jstjohn/SeqPrep",'+
'"/jstjohn/SimSeq",'+
'"/jtaghiyar/kronos.Keywords:",'+
'"/jts/nanopore-paper-analysis",'+
'"/julienfumey/popsim",'+
'"/julien-roux/Roux_Liu_and_Robinson-Rechavi_2016",'+
'"/jwertz01/annotator-comparison",'+
'"/jyu429/IGHV-genotyping",'+
'"/kaazemi/FCSS",'+
'"/kakitone/BIGMAC",'+
'"/Kalirad/RNA_folding_model_of_DMIs",'+
'"/kalleknast/head-tracker",'+
'"/KaneLab",'+
'"/KarchinLab/2020plus",'+
'"/karl616/gNOMePeaks",'+
'"/kassambara/easyGgplot2",'+
'"/katholt/Kaptive",'+
'"/katholt/RedDog",'+
'"/katholt/srst2",'+
'"/katholt/srst2",'+
'"/kauralasoo/rasqual",'+
'"/kauralasoo/reviseAnnotations",'+
'"/kbase",'+
'"/kbhoehn/IgPhyML",'+
'"/kbroman/simcross",'+
'"/kc-lab/dms2dfe",'+
'"/kdmurray91/kwip",'+
'"/kelwyres/Kp-cps-loci.git",'+
'"/kendrickkay/knkutils/tree/master/imageprocessing",'+
'"/kern-lab/discoal",'+
'"/kern-lab/discoal_multipop",'+
'"/kern-lab/shIC",'+
'"/khayer/benchmarking_scripts",'+
'"/KHP-Informatics/TC",'+
'"/khramts/assocplots",'+
'"/KiddLab/QuicK-mer",'+
'"/kieranrcampbell/embeddr",'+
'"/kieranrcampbell/gpseudotime",'+
'"/kieranrcampbell/ouija",'+
'"/kieranrcampbell/pseudogp.413",'+
'"/kingaa/genpomp",'+
'"/Kingsford-Group/catfish",'+
'"/Kingsford-Group/ribomap/blob/master/README.md",'+
'"/kingsleyevan/phylo_epk",'+
'"/kkdey/CountClust",'+
'"/kloetzl/biotwiddle",'+
'"/knausb",'+
'"/KnowEnG/ProGENI",'+
'"/koadman/longas",'+
'"/konradjk/exac_browser",'+
'"/konradjk/loftee",'+
'"/konradjk/loftee>",'+
'"/KordingLab/DAD",'+
'"/ksahlin/BESST",'+
'"/ksahlin/GetDistr",'+
'"/ksahlin/GetDistr",'+
'"/kshitijtayal/GPhase/",'+
'"/ktrappe/daisy",'+
'"/kundajelab/dragonn",'+
'"/kundajelab/keras/tree/keras_1",'+
'"/kveeramah/aDNA_GenoCaller. This protocol substantially ",'+
'"/kvougas/Vougas_DeepLearning",'+
'"/kwikteam/klustakwik2/",'+
'"/kyungtaekLIM/PSIBLASTexB",'+
'"/lamarck2008/LEM",'+
'"/lanagarmire/cox-nnet",'+
'"/lanagarmire/SSrGE",'+
'"/LANL-364",'+
'"/LANL-Bioinformatics/PhaME",'+
'"/LaoZZZZZ/bartender-1.1",'+
'"/LarracuenteLab/Khost_Eickbush_Larracuente2016",'+
'"/laurenemberson/EmbersonZinszerMCPA_analysesFromPaper",'+
'"/lauringlab/variant_pipeline",'+
'"/lbaeten/DivChangeResponse",'+
'"/leekgroup/genesigprecision",'+
'"/leekgroup/recount",'+
'"/leffj/mctoolsr",'+
'"/lengning/OEFinder",'+
'"/lengning/SCPattern",'+
'"/LennonLab/radiolyticCH4",'+
'"/lganel/SVScore",'+
'"/lh3/bgt",'+
'"/lh3/bwa/tree/master/bwakit",'+
'"/lh3/psmc2",'+
'"/lh3/seqtk",'+
'"/lh3/seqtk",'+
'"/lh3/sgdpfermi",'+
'"/lh3/wgsim",'+
'"/lhhunghimself/fastBMA",'+
'"/lhhunghimself/fast_protein_cluster",'+
'"/LiamDBailey/climwin",'+
'"/limno/illumitag/",'+
'"/linsalrob/qudaich/",'+
'"/linzx06/AC-PCA",'+
'"/Liuy12/XBSeq",'+
'"/llerussell/paq2py",'+
'"/lmweber/cytometry-clustering-comparison",'+
'"/local-minimum/scanomatic/",'+
'"/LohmuellerLab/fitdadi",'+
'"/loire/GalapagosData_And_Script/",'+
'"/lomereiter/sambamba",'+
'"/lorinanthony/MEPIT",'+
'"/lsncibb/microbiomeGWAS",'+
'"/lstevison/great-ape-recombination/",'+
'"/LTLA",'+
'"/lucapinello/CRISPResso",'+
'"/LucksLab/Hu_RNA_Circuit_Parameterization_ACSSynBio_2015",'+
'"/LucksLab/spats",'+
'"/luoyunan/DTINet",'+
'"/lutzfischer/xiFDR",'+
'"/lvdmaaten/bhtsne/",'+
'"/lwlss/Holstein2016",'+
'"/lyd0527/mInDel",'+
'"/machenslab/dPCA",'+
'"/machinegun/hi-c-scaffold",'+
'"/macmanes-lab/peer_reproductive-transcriptome/blob/master/code.md",'+
'"/ma-compbio/Weaver",'+
'"/MadsAlbertsen/multimetagenome;",'+
'"/magicDGS/ReadTools",'+
'"/mahyam/DNA-methylation-and-metabolism-R-code",'+
'"/mailund/admixture_graph",'+
'"/mailund/IMCoalHMM",'+
'"/maljoras/xyTracker",'+
'"/marbl/canu",'+
'"/marbl/harvest",'+
'"/marbl/mash",'+
'"/MarBL/MashMap",'+
'"/marcelm/cutadapt;",'+
'"/marcottelab/boolean",'+
'"/marcottelab/Gene-Ages",'+
'"/marcottelab/protein_complex_maps_public",'+
'"/marcus1487/nanoraw",'+
'"/maresther23/boolnet-perturb",'+
'"/marianattestad/assemblytics",'+
'"/markrobinsonuzh/benchmarkR",'+
'"/markrobinsonuzh/diff_splice_paper",'+
'"/markrobinsonuzh/iCOBRA",'+
'"/martinosorb/herding-spikes",'+
'"/Martinsos/edlib",'+
'"/marvinboe/reTASEP",'+
'"/materechm/plabData/blob/master/scripts/conservation_anal",'+
'"/Mathelab/ALTRE",'+
'"/mathii/spectrum",'+
'"/MattHartfield/TwoAdvSelfSims",'+
'"/matthiaskoenig/multiscale­galactose",'+
'"/MaximumEntropy/UPSITE.git",'+
'"/mbdoud/Compare-NP-Preferences",'+
'"/mbi2gs",'+
'"/mbontrager/primate_ca",'+
'"/mbusby/",'+
'"/mcianfrocco/Cianfrocco-andLeschziner-2014-EMCloudProcessing/",'+
'"/McKinlab/Coculture-Mutualism",'+
'"/mcstitzer/agpv4_te_annotation/tree/master/ncbi_pseudomolecule",'+
'"/mcvaneede/RMINC",'+
'"/mdcao/npScarf",'+
'"/mdfortune/",'+
'"/MDU-PHL/ngmaster",'+
'"/medvedevgroup/bloomtree-allsome",'+
'"/medvedevgroup/varmatch",'+
'"/mel-astar/mel-ngs/blob/master/mel-chipseq/chipseq-1034",'+
'"/melodi-lab/submodular-selection-of-assays",'+
'"/melop/admixem",'+
'"/mendessoares/MMinte",'+
'"/meren/anvio",'+
'"/merenlab/illumina-utils",'+
'"/meren/reads-for-assembly",'+
'"/mevers/RNAModR",'+
'"/mfcovington/snps-from-rils",'+
'"/mfcovington/SNPtools",'+
'"/mfumagalli/",'+
'"/mg14/AML-multistage",'+
'"/mgonzalezporta/SwitchSeq",'+
'"/Microbiology/ViromeVarScripts",'+
'"/MicrosoftGenomics/FaST-LMM/tree/master/fastlmm",'+
'"/middleprofessor/happiness",'+
'"/MikeAxtell/ShortStack/releases",'+
'"/mikel-egana-aranguren/SADI-Galaxy",'+
'"/mikelove/",'+
'"/millanek/fineRADstructure",'+
'"/millanek/trio-sga",'+
'"/mills-lab/spectre",'+
'"/millslab/svelter",'+
'"/min110/mislabeled.samples.identification",'+
'"/mlandis/biogeo_dating",'+
'"/mleibman/SlickGrid/",'+
'"/mlibbrecht/submodular_sequence_",'+
'"/mlin/PhyloCSF.git",'+
'"/mlin/PhyloCSF/",'+
'"/mmatschiner/F4",'+
'"/mmclaren42/valley-crossing-220",'+
'"/mnewberry/XXXXXXX",'+
'"/mobleylab/benchmarksets",'+
'"/ModelSEED/ModelSEEDDatabase/tree/master/Biochemistry",'+
'"/MODICT/MODICT.Conclusion:",'+
'"/molgenis/gavin",'+
'"/molgenis/molgenis-pipelines",'+
'"/molpopgen/msstats",'+
'"/MonkeyLB/hicrep",'+
'"/morinlab/tools-morinlab",'+
'"/mourisl/Lighter/",'+
'"/MPBA/renette",'+
'"/mpdunne/orthofiller",'+
'"/MRC-CLIMB/",'+
'"/mreppell/Karp",'+
'"/mrhunsaker/Change_Point",'+
'"/mrmckain/AJB_2015_Mimulus_Allopolyploidy",'+
'"/mrmckain/FASTKs",'+
'"/MRtrix3/mrtrix3",'+
'"/msettles/dbcAmplicons",'+
'"/msmbuilder/",'+
'"/msproteomicstools/msproteomicstools",'+
'"/mtw/Bio-ViennaNGS",'+
'"/muhligs/regmex",'+
'"/MulletLab/SorghumReconstructionAndPhenotyping",'+
'"/murphycj/AGFusion",'+
'"/mvboven/cmv-serology",'+
'"/MVZSEQ.!The!workflow!removes!duplicate",'+
'"/mw55309/poRe_docs",'+
'"/mwpennell/phyloPCA.200",'+
'"/mzwiessele/topslam",'+
'"/najoshi/sabre",'+
'"/najoshi/sickle",'+
'"/najoshi/sickle",'+
'"/najoshi/sickle2011",'+
'"/NAL-i5K/I5KNAL_OGS/wiki/QC-phase",'+
'"/narechan/clusterflock",'+
'"/naturalis/imgpheno",'+
'"/naturalis/monophylizer/tree/v1.0.1.!2015.!588",'+
'"/nedelec/cytosim",'+
'"/neherlab/python_",'+
'"/nelas/color-blind-luts",'+
'"/nello/region_matrix",'+
'"/nellore/rail-dbgap",'+
'"/nellore/runs",'+
'"/nellore/runs/blob/master/sra/rip_annotated_",'+
'"/nerobbin/20161214_hydropatterning",'+
'"/NESCent/r-popgen-hackathon",'+
'"/NeuralEnsemble/NeuroTools",'+
'"/NeuroanatomyAndConnectivity/ConjunctiveContinuousPerformanceTask For ",'+
'"/neuroelectro",'+
'"/neurosynth/neurosynth",'+
'"/Nextomics/NextSV",'+
'"/ngcrawford/2232505",'+
'"/nghiavtr/ISOP",'+
'"/nh13/DWGSIM/",'+
'"/nicfel/The-Structured-Coalescent.git",'+
'"/nignatiadis/ihwPaper",'+
'"/NIHOPA",'+
'"/NilsWinter/matlab-bayesianestimation/blob/master/README.md",'+
'"/nipy/mindboggle/issues",'+
'"/nipy/PySurfer",'+
'"/nluhmann/AGapEs",'+
'"/nmdavies/UKbiobankROSLA",'+
'"/nmdp-bioinformatics/genotype-list",'+
'"/NMML/pref_sampling/.178",'+
'"/nstenz",'+
'"/nvalimak/fsm-lite",'+
'"/NYU-BFX/hic-bench/",'+
'"/oesteban",'+
'"/oganm",'+
'"/ohnosequences/mg7",'+
'"/oicr-gsi/debarcer",'+
'"/omanor/MUSiCC",'+
'"/OmnesRes/pan_cancer",'+
'"/opetchey/ecopredtools",'+
'"/orrzor/2016_NP_MxA_paper",'+
'"/Oshlack/Lace/",'+
'"/OSSCB2013",'+
'"/pachterlab/bears_analyses",'+
'"/pachterlab/PROBer_paper_analysis",'+
'"/pachterlab/zika/",'+
'"/PacificBiosciences/cDNA_primer",'+
'"/PacificBiosciences/DevNet/wiki/Datasets",'+
'"/PacificBiosciences/FALCON/",'+
'"/PacificBiosciences/FALCON-integrate",'+
'"/PacificBiosciences/GenomicConsensus/blob/master/doc/FAQ.rst",'+
'"/PacificBiosciences/pbccs",'+
'"/PacificBiosciences/pbdagcon",'+
'"/pagnani/PlmDCA",'+
'"/PalEON-Project/stepps-calibration",'+
'"/PalEON-Project/WitnessTrees",'+
'"/pandegroup/openmm",'+
'"/pandegroup/pdbfixer",'+
'"/pasculorente/Mist",'+
'"/Pas-Kapli/mptp",'+
'"/paula-tataru/SpikeyTree",'+
'"/pbastide/",'+
'"/pberkes/neuro-kl",'+
'"/pblischak/polyfreqs-ms-data",'+
'"/pedroj/MS_Network-Sampling",'+
'"/pellinglab",'+
'"/pennekampster/bemovi",'+
'"/PeteHaitch/XGWAS",'+
'"/petercombs/EisenLab-Code",'+
'"/petrelharp/euroibd",'+
'"/petrelharp/local_pca",'+
'"/PF2-pasteur-fr/SARTools/",'+
'"/pgnelson/emergent_capacitance",'+
'"/phac-nml/neptune",'+
'"/PhDP/Articles",'+
'"/phenoscape",'+
'"/philres/nextgenmap-lr",'+
'"/phrh/PredRAD",'+
'"/phylesystem",'+
'"/PickrellLab/gwas-­‐pw-­‐paper/tree/master/all_single",'+
'"/pierpal/ARGON",'+
'"/pierpal/IBDMUT.752",'+
'"/pillowlab/CDMentropy",'+
'"/pillowlab/StepRampMCMC",'+
'"/piquelab/QuASAR",'+
'"/PitchInteractiveInc/Phinch/",'+
'"/pkerpedjiev/forgi",'+
'"/pmb59/fCCAC/",'+
'"/PMBio/f-scLVM",'+
'"/PMBio/limix",'+
'"/PMBio/limix",'+
'"/PMBio/scLVM/blob/master/data/Tcell/data_Tcells.Rdata",'+
'"/poeli/GOTTCHA",'+
'"/PoisonAlien/maftools",'+
'"/PoisotLab/EcologicalNetwork.jl.3",'+
'"/poldrack/myconnectome­vm ",'+
'"/pomo-dev/PoMo",'+
'"/pontikos/phenopolis",'+
'"/popgenomics/popPhylABC",'+
'"/potamomics-scripts",'+
'"/ppgardne/RMfam",'+
'"/prefixcommons/prefixes",'+
'"/premgopalan/terastructure",'+
'"/preprocessed-connectomes-project/",'+
'"/preprocessed-connectomes-project/adhd200_athena_scripts",'+
'"/PriceLab/snapr",'+
'"/pshved/timeout",'+
'"/pstew/escape_excel",'+
'"/psychoinformatics-de/studyforrest-data-multires7t",'+
'"/PsychoinformaticsLab/nipymc",'+
'"/PyProphet",'+
'"/qfma/duf1220",'+
'"/QTB-HHU",'+
'"/QTB-HHU/ModelHeatShock.15",'+
'"/QuackenbushLab/MONSTER",'+
'"/quantixed/PaperCode/",'+
'"/r3fang/PLACseq",'+
'"/rajanil/msCentipede",'+
'"/rajewsky-lab/dropbead",'+
'"/raquele/GeNNet",'+
'"/rasilab/ferrin_1",'+
'"/ratschlab/mmr.Supplementary",'+
'"/ratschlab/ribodiff",'+
'"/ratschlab/spladder",'+
'"/RBankoff/BEAT",'+
'"/rcannood/SCORPIUS",'+
'"/rcavalcante",'+
'"/RCollins13/CNView",'+
'"/rcristofari/RAD-Scripts.git",'+
'"/rdejonge/genomics",'+
'"/rdiaz02/OncoSimul",'+
'"/Read­Lab­Confederation/staph_metagenome_subtypes. ",'+
'"/RealTimeGenomics/rtg-tools",'+
'"/regulomics/biopython",'+
'"/RemkoDuursma/baadanalysis.165",'+
'"/reptalex/phylofactor.378",'+
'"/restful-open-annotation/",'+
'"/RGLab/MAST",'+
'"/RGLab/MAST",'+
'"/rhodricusack/automaticanalysis",'+
'"/rhr/lagrange-cpp",'+
'"/richfitz/phyndr",'+
'"/rich-iannone/stationaRy",'+
'"/ririzarr/bumphunter",'+
'"/rlgoldfeder/coverageOfKeyGenes",'+
'"/rmcclosk/netabc",'+
'"/rmcelreath/parasiticbehaviorsim",'+
'"/roblanf/",'+
'"/rohanmaddamsetti/Ara-1_Genotyping",'+
'"/ropensci/rgbif",'+
'"/roshchupkin/HASE/;",'+
'"/rozovr/Recycler",'+
'"/rr1859/R.4Cker",'+
'"/rrwick/Bandage",'+
'"/rrwick/Unicycler",'+
'"/rrwick/Unicycler",'+
'"/rsbaucom/MatingSystem2015",'+
'"/ruanjue/smartdenovo",'+
'"/ruolin/Strawberry",'+
'"/russcd/Ancestry_HMM",'+
'"/rvaser/sword",'+
'"/ryanlayer/gqt",'+
'"/saemi/plast2phy",'+
'"/saezlab/kinact/",'+
'"/saezlab/liverx",'+
'"/saezlab/protein_attenuation",'+
'"/saezlab/yeast_phospho",'+
'"/safisher/ngs/wiki/ngs_TRIM>",'+
'"/sahilseth/flowr",'+
'"/saketkc/biojs-genetic-variation-viewerA",'+
'"/samtools/BCFtools",'+
'"/samtools/hts-specs/",'+
'"/sandipchatterjee/blazmass_compil",'+
'"/sandywang/GRETNA",'+
'"/sanger-pathogens/snp_sites",'+
'"/sanger-pathogens/vr-codebase",'+
'"/SangerProteomics/PoGo",'+
'"/sarahhcarl/flychip/wiki/BasicK",'+
'"/sarahmid/PESS",'+
'"/sarbal/EGAD",'+
'"/sarisbro.178",'+
'"/sarisbro.220",'+
'"/sarisbro/AEGIS",'+
'"/Sashkow/placenta-preeclampsia",'+
'"/satoken/practip",'+
'"/sbenz/Paradigm",'+
'"/schatzlab/genomescope",'+
'"/schatzlab/genomescope.git",'+
'"/schlegelp/CATMAID-to-Blender",'+
'"/SchlossLab/Baxter_FITs_BMCCancer_2016",'+
'"/SchlossLab/Schloss_Census2_mBio_2016.357",'+
'"/schmelling/reciprocal",'+
'"/Schraiber/quant",'+
'"/sebastianduchene",'+
'"/secastel/aFC",'+
'"/secastel/phaser",'+
'"/Sephiroth1st/EquidistanceScript",'+
'"/seqcode/sequnwinder",'+
'"/sequana/sequana",'+
'"/sequencing/test/blob/master/markdown/manual.md",'+
'"/Setfelix/ADRes/tarball/master",'+
'"/seth-ament/hd-trn",'+
'"/sggaffney/pathscore",'+
'"/shahmoradi/cordiv",'+
'"/shahpr/RiboViz",'+
'"/sharpton/shotmap",'+
'"/SheffieldML/GPy",'+
'"/SheffieldML/GPy",'+
'"/shendurelab/Cas9FateMapping",'+
'"/SIMEXP/mcinet",'+
'"/SiminaB/Fdr-regression",'+
'"/simongog/sdsl-lite",'+
'"/simonvh/fluff",'+
'"/simtk/IRMSD",'+
'"/sjczheng/EpiDISH",'+
'"/sjspielman/dnds",'+
'"/sjspielman/pyvolve",'+
'"/sknepneklab/SAMoS",'+
'"/skumagai/selfingsim",'+
'"/slisovski/Geolocator-ArcticWader-BreedingSiteEstimation",'+
'"/smangul1/HapIso/",'+
'"/smangul1/UMI-Reducer/wiki/",'+
'"/smfleming/HMM",'+
'"/smirarab/sepp.git",'+
'"/smithmj/Antibiotic-Cycling",'+
'"/smorfopoulou/metaMix",'+
'"/snacktavish/TreeToReads",'+
'"/snacktavish/TreeToReads",'+
'"/snayfach/MicrobeCensus",'+
'"/snayfach/MicrobeCensus",'+
'"/snayfach/MIDAS",'+
'"/soccin/S1Seq",'+
'"/soedinglab/BaMMmotif",'+
'"/soedinglab/mmseqs2",'+
'"/sofroniewn/2pRAM-paper",'+
'"/sophie63/FlyLFM",'+
'"/soumitrakp/ems2.git",'+
'"/SoyeonA/aBayesQR",'+
'"/spacocha/Distribution-based-clustering",'+
'"/SpeciesFileGroup/nomen",'+
'"/spulido99/SSA",'+
'"/spyder-ide/spyder",'+
'"/srutschmann/python_scripts/blob/master/extract_introns.py",'+
'"/sschmeier/irndb2",'+
'"/sstevens2",'+
'"/stajichlab/FGMP",'+
'"/stamatak/",'+
'"/stamatak/softwareQuality",'+
'"/stamatak/standard-RAxML",'+
'"/stamatak/tree-viz-issues",'+
'"/stan-dev/rstan/wiki/Install-Rtools-for-Windows",'+
'"/statgen/verifyBamID",'+
'"/StefanReuscher/ABHgenotypeR",'+
'"/stephaneguindon/phyml",'+
'"/stephaniehicks/qsmooth",'+
'"/stephaniehicks/quantroSim",'+
'"/stephenfloor/tripseq-analysis",'+
'"/stephens999/ashr",'+
'"/stephenslab/mashr",'+
'"/stephenslab/rss",'+
'"/stephenturner/qqman",'+
'"/StoreyLab/",'+
'"/StoreyLab/gcat/",'+
'"/stschiff/hfit",'+
'"/stschiff/msmc2",'+
'"/stschiff/rarecoal",'+
'"/stuberlab/PC_opto_fMRI_analysis",'+
'"/SuLab/WikidataIntegrator",'+
'"/susjoh/crimaptools",'+
'"/suweis/Effect-of-Localization-on-the-Stabilityof-Mutualistic-Ecological-Networks",'+
'"/svendaehne/matlab_SPoC/tree/master/SSD",'+
'"/svmzhang/AGOUTI",'+
'"/svmzhang/make_life_easier",'+
'"/svviz/svviz",'+
'"/svviz/svviz. ",'+
'"/sys-bio/sbnw",'+
'"/sys-bio/simplesbml",'+
'"/systems-immunology-roslin-institute/ImSig",'+
'"/szpiech/selscan",'+
'"/tanghaibao/goatools",'+
'"/taoliu/MACS",'+
'"/taoliu/MACS/tree/macs_v1",'+
'"/taoliu/MACS/wiki/Build-Signal-Track",'+
'"/tare/GPMicrobiome",'+
'"/tarunaaggarwal/G.morbida.Comp.Gen",'+
'"/TBiophysG/VBDCMM”",'+
'"/tderrien/FEELnc",'+
'"/TeamErlich/dna-fountain",'+
'"/TeamErlich/dna-landcompass",'+
'"/team-pltb",'+
'"/teichlab/tracer. This performs ",'+
'"/telenius/captureC/releases",'+
'"/TGAC/KAT",'+
'"/TGenNorth/ISGPipeline",'+
'"/TGenNorth/NASP/releases/tag/v0.9.6",'+
'"/tgouhier/biwavelet",'+
'"/TheaWhitman/PyOM",'+
'"/theis188/py_emra",'+
'"/The-Sequence-Ontology/Specifications/blob/master/gff3.md",'+
'"/thh32/Spherical",'+
'"/thierrygosselin/stackr",'+
'"/thijsjanzen/Haplotype-Block-Dynamics647",'+
'"/thk2008/methylseqplatformcomparison",'+
'"/ThomasMiconi/BiologicallyPlausibleLearningRNN",'+
'"/timotheenivalis/SelRepSel.21",'+
'"/tknijnen/LOBICO",'+
'"/tkuhn/bel2nanopub/",'+
'"/tncoulson/QG-meets-IPM-figure-code/tree/master.289",'+
'"/tombergk/FVL_SUP",'+
'"/TommyBlanchard/StanNeuronModelling",'+
'"/torognes/vsearch",'+
'"/tracysmith/RGAPepPipe",'+
'"/tracysmith/RGAPepPipe",'+
'"/traitecoevo/growth",'+
'"/transcript/SAMSA",'+
'"/trayc7/FDPPDIV",'+
'"/trgao10/PuenteAlignment",'+
'"/trinityrnaseq/trinityrnaseq/releases",'+
'"/trinityrnaseq/trinityrnaseq/wiki/RNA-Seq-Read-Representation-byTrinity-Assembly",'+
'"/trinityrnaseq/trinityrnaseq/wiki/Transcriptome-Contig-Nx-and-ExN50-stats",'+
'"/tritemio",'+
'"/tsackton/musca-immunity",'+
'"/tseemann/abricate",'+
'"/tseemann/snippy",'+
'"/tshmak/lassosum",'+
'"/tslumley/bigQF",'+
'"/tszalay/poisson",'+
'"/ttesileanu/twostagelearning",'+
'"/ttimbers/Million-Mutation-Project-dye-filling-SKAT.git",'+
'"/twestbrookunh/paladin",'+
'"/tylerhether",'+
'"/UCanCompBio/Avoidance",'+
'"/UCanCompBio/deltaBS",'+
'"/UCanCompBio/speed-vsaccuracy-meta-analysis",'+
'"/ucicbcl/DanQ",'+
'"/uci-cbcl/D-GEX",'+
'"/uci-cbcl/HLA-bind",'+
'"/uclinfectionimmunity/PCRsim.!Briefly",'+
'"/ucscGenomeBrowser/kent/tree/master/src/hg/makeDb/crisprTrack",'+
'"/udo-stenzel/mapping-iterative-assembler",'+
'"/udo-stenzel/network-aware-bwa",'+
'"/ueser/FIDDLE",'+
'"/ugcd/solarius",'+
'"/uiocels/Repeats",'+
'"/UMN-285",'+
'"/umutcaglar/ecoli_multiple_growth_conditions",'+
'"/uriba/proteome-analysis",'+
'"/valafarlab/biodiff",'+
'"/varapp",'+
'"/varnerlab/POETs.jl",'+
'"/varnerlab/POETs.jl.408",'+
'"/VCCRI/Falco/",'+
'"/VCCRI/PBrowse.Supplementary",'+
'"/vcflib/vcflib",'+
'"/vegandevs/vegan",'+
'"/vgteam/vg",'+
'"/vistalab/vistasoft",'+
'"/vqv/ggbiplot",'+
'"/VRam142/combinatorial",'+
'"/wacguy/Simple",'+
'"/WagnerLabPapers",'+
'"/waldronlab/curatedMetagenomicData/",'+
'"/Washington-University/Pipelines",'+
'"/wassermanlab/CAGEd-oPOSSUM",'+
'"/weikanggong/BWAS",'+
'"/WeiqiangZhou/BIRD",'+
'"/weissmanlab/magicbeta",'+
'"/WeitzGroup/DilutionMethod-NicheCompetition",'+
'"/WeitzGroup/VMR-Lysis-Lysogeny",'+
'"/wenjiegroup/PEDLA",'+
'"/wgar84",'+
'"/wiedenhoeft/HaMMLET/tree/",'+
'"/wiheto/teneto",'+
'"/wilkelab/EBOV",'+
'"/wilkelab/Ecoli",'+
'"/wilkelab/eGFP_deletion_prediction",'+
'"/wilkelab/influenza",'+
'"/wilkelab/influenza_H3N2_passaging",'+
'"/willmclaren",'+
'"/WilsonSayresLab/MMB_apes",'+
'"/WilsonSayresLab/PARdiversity",'+
'"/WinawerLab/BOLD_LFP",'+
'"/wingolab-org/pecaller",'+
'"/WormLabCaltech/",'+
'"/xapple/seqenv",'+
'"/xavierdidelot/TransPhylo",'+
'"/xiangfstats/GenieR",'+
'"/xiaochuanle/MECAT",'+
'"/xjwanglab/pyrl",'+
'"/xqwen/dap",'+
'"/xqwen/integrative/",'+
'"/xqwen/torus/",'+
'"/xuebingwu/kpLogo",'+
'"/xypan1232/iDeep",'+
'"/xzhuo/orthologusLTR.git",'+
'"/yangzhi-psy/gRAICAR",'+
'"/yifeng-li/DECRES",'+
'"/yiminghu/AnnoPred",'+
'"/yjingj/SFBA",'+
'"/ymatts/D3M/",'+
'"/ymatts/phyC",'+
'"/yoheirosen/vg",'+
'"/YosefLab/FastProject/",'+
'"/YosefLab/TRAPeS",'+
'"/yuelab/BUTLRTools",'+
'"/yujin-chung/MIST.git",'+
'"/YunjiaoWang152",'+
'"/Yves-CHEN/sCNAphase",'+
'"/z0on/GO_MWU",'+
'"/z0on/tag-based_RNAseq",'+
'"/zdealveindy/weimea/",'+
'"/zeux/pugixml",'+
'"/zhandong/XMRF",'+
'"/zhangsaithu/tide_demo",'+
'"/ZhiGroup/RaPID",'+
'"/zhouxiaofan1983/iWGS",'+
'"/ZhuangLab/storm-analysis",'+
'"/zibraproject/zika-pipeline",'+
'"/zuoxinian/CCS",'+
'"/zyndagj/repliscan"]'+
'}';

var people = require('../lib/switcher');
var scrapedrepos = JSON.parse(text);

for(i = 0; i<scrapedrepos.repos.length; i++){
	var url = scrapedrepos.repos[i];
	people(url, function(err, data){
	})
}


