var text = '{ "brepos" :' + 
'[ "https://github.com/21zhangqiong/MEG_Alignment",'+
'"https://github.com/23andMe/yhaplo",'+
'"https://github.com/4ureliek/ReannTE",'+
'"https://github.com/AdelaideBioinfo/retrotransposonAccumulation",'+
'"https://github.com/AlastairKerr/Robson2016",'+
'"https://github.com/AllonKleinLab/SPRING/",'+
'"https://github.com/AnaPoets/BarleyLandraces",'+
'"https://github.com/ArtRand/signalAlign",'+
'"https://github.com/ArunasRadzvilavicius/GermlineEvolution",'+
'"https://github.com/BEAST2-Dev/bModelTest",'+
'"https://github.com/BinPro/CONCOCT",'+
'"https://github.com/BioDepot/BioDepot-workflow-builder",'+
'"https://github.com/BiologicalRecordsCentre/RangeChangeSims",'+
'"https://github.com/Blahah/transrate",'+
'"https://github.com/Bohdan-Khomtchouk/ENCODE_TF_geneXtendeR_analysis",'+
'"https://github.com/Bohdan-Khomtchouk/Microscope",'+
'"https://github.com/Bohdan-Khomtchouk/shinyheatmap",'+
'"https://github.com/CGATOxford/UMI-tools",'+
'"https://github.com/CGRL-QB3-UCBerkeley/denovoTargetCapturePopGen",'+
'"https://github.com/CMPG/ADMRE",'+
'"https://github.com/CNSGenomics/impute-pipe",'+
'"https://github.com/COMBINE-lab/matryoshka",'+
'"https://github.com/COMBINE-lab/quark",'+
'"https://github.com/Caetanods/Dipsadidae_color_evolution",'+
'"https://github.com/Caged/d3-tip",'+
'"https://github.com/CaioFreire/CUB",'+
'"https://github.com/CampagneLaboratory/goby3",'+
'"https://github.com/CampagneLaboratory/variationanalysis",'+
'"https://github.com/CellProfiler/CellProfiler-Analyst",'+
'"https://github.com/Chris1221/goldi",'+
'"https://github.com/ChrisHIV/shiver",'+
'"https://github.com/ChristopherWilks/snaptron",'+
'"https://github.com/Cibiv/Teaser",'+
'"https://github.com/CobraLab/MAGeTbrain",'+
'"https://github.com/DL42/GOFish",'+
'"https://github.com/DNAworker/DNAlogo",'+
'"https://github.com/DanChitwood/PassifloraLeaves",'+
'"https://github.com/Danko-Lab/rtfbs_db",'+
'"https://github.com/DecodeGenetics/chopBAI",'+
'"https://github.com/DeveauP/QuantumClone/",'+
'"https://github.com/DiegoCambuy/CAT",'+
'"https://github.com/DworkinLab/TestaDworkin2016DGE",'+
'"https://github.com/ENCODE-DCC/snovault/",'+
'"https://github.com/EarnshawLab/nanoRF",'+
'"https://github.com/EnvGen/Tutorials",'+
'"https://github.com/Ettwiller/TSS/",'+
'"https://github.com/FRED-2/OptiType",'+
'"https://github.com/Fei-Lu/FastCall",'+
'"https://github.com/FrancescaMancini/Flickr-API",'+
'"https://github.com/FrankD/fuser",'+
'"https://github.com/GNilsonne/IL6_diurnal",'+
'"https://github.com/Generade-nl/TULIP",'+
'"https://github.com/GenomicsCoreLeuven/GBSX",'+
'"https://github.com/GeorgievLab/CeCe/",'+
'"https://github.com/Gibbsdavidl/miergolf",'+
'"https://github.com/GiliG/NetStruct",'+
'"https://github.com/GreallyLab/Nadel-et-al.-2015",'+
'"https://github.com/GreenleafLab/NucleoATAC",'+
'"https://github.com/HGID/WES_vs_WGS",'+
'"https://github.com/HongjianLi/idock",'+
'"https://github.com/HudsonAlpha/aRNAPipe",'+
'"https://github.com/HullUni-bioinformatics/metaBEAT",'+
'"https://github.com/ICBI/viGEN/",'+
'"https://github.com/INCF/openfmri2bids",'+
'"https://github.com/ISA-tools/NanoMaton",'+
'"https://github.com/Illumina/ExpansionHunter",'+
'"https://github.com/Illumina/canvas",'+
'"https://github.com/Illumina/manta",'+
'"https://github.com/Illumina/pyflow",'+
'"https://github.com/Illumina/tHapMix",'+
'"https://github.com/IlyaLab/CombiningDependentPvaluesUsingEBM",'+
'"https://github.com/InouyeLab/NetRep",'+
'"https://github.com/JeremyHorst/MinorityReport",'+
'"https://github.com/Jfortin1/HiC_AB_Compartments",'+
'"https://github.com/JohnEPool/SIBSAM1",'+
'"https://github.com/JohnReid/DeLorean/",'+
'"https://github.com/JovMaksimovic/methyl-seq_bpipe",'+
'"https://github.com/KHP-Informatics/TC",'+
'"https://github.com/KarchinLab/2020plus",'+
'"https://github.com/KiddLab/QuicK-mer",'+
'"https://github.com/Kingsford-Group/catfish",'+
'"https://github.com/KnowEnG/ProGENI",'+
'"https://github.com/KordingLab/DAD",'+
'"https://github.com/LANL-Bioinformatics/PhaME",'+
'"https://github.com/LaoZZZZZ/bartender-1.1",'+
'"https://github.com/LarracuenteLab/Khost_Eickbush_Larracuente2016",'+
'"https://github.com/LennonLab/radiolyticCH4",'+
'"https://github.com/LiamDBailey/climwin",'+
'"https://github.com/Liuy12/XBSeq",'+
'"https://github.com/LohmuellerLab/fitdadi",'+
'"https://github.com/LucksLab/Hu_RNA_Circuit_Parameterization_ACSSynBio_2015",'+
'"https://github.com/LucksLab/spats",'+
'"https://github.com/MDU-PHL/ngmaster",'+
'"https://github.com/MPBA/renette",'+
'"https://github.com/MRtrix3/mrtrix3",'+
'"https://github.com/MarBL/MashMap",'+
'"https://github.com/Martinsos/edlib",'+
'"https://github.com/Mathelab/ALTRE",'+
'"https://github.com/MattHartfield/TwoAdvSelfSims",'+
'"https://github.com/McKinlab/Coculture-Mutualism",'+
'"https://github.com/Microbiology/ViromeVarScripts",'+
'"https://github.com/MonkeyLB/hicrep",'+
'"https://github.com/MulletLab/SorghumReconstructionAndPhenotyping",'+
'"https://github.com/NESCent/r-popgen-hackathon",'+
'"https://github.com/NYU-BFX/hic-bench/",'+
'"https://github.com/NeuralEnsemble/NeuroTools",'+
'"https://github.com/Nextomics/NextSV",'+
'"https://github.com/OmnesRes/pan_cancer",'+
'"https://github.com/Oshlack/Lace/",'+
'"https://github.com/PF2-pasteur-fr/SARTools/",'+
'"https://github.com/PMBio/f-scLVM",'+
'"https://github.com/PMBio/limix",'+
'"https://github.com/PacificBiosciences/FALCON-integrate",'+
'"https://github.com/PacificBiosciences/FALCON/",'+
'"https://github.com/PacificBiosciences/cDNA_primer",'+
'"https://github.com/PacificBiosciences/pbccs",'+
'"https://github.com/PacificBiosciences/pbdagcon",'+
'"https://github.com/Pas-Kapli/mptp",'+
'"https://github.com/PeteHaitch/XGWAS",'+
'"https://github.com/PitchInteractiveInc/Phinch/",'+
'"https://github.com/PoisonAlien/maftools",'+
'"https://github.com/PriceLab/snapr",'+
'"https://github.com/PsychoinformaticsLab/nipymc",'+
'"https://github.com/QuackenbushLab/MONSTER",'+
'"https://github.com/RBankoff/BEAT",'+
'"https://github.com/RCollins13/CNView",'+
'"https://github.com/RGLab/MAST",'+
'"https://github.com/RealTimeGenomics/rtg-tools",'+
'"https://github.com/SIMEXP/mcinet",'+
'"https://github.com/Sashkow/placenta-preeclampsia",'+
'"https://github.com/Sephiroth1st/EquidistanceScript",'+
'"https://github.com/SheffieldML/GPy",'+
'"https://github.com/SiminaB/Fdr-regression",'+
'"https://github.com/SoyeonA/aBayesQR",'+
'"https://github.com/SpeciesFileGroup/nomen",'+
'"https://github.com/StefanReuscher/ABHgenotypeR",'+
'"https://github.com/StoreyLab/gcat/",'+
'"https://github.com/SuLab/WikidataIntegrator",'+
'"https://github.com/TGAC/KAT",'+
'"https://github.com/TGenNorth/ISGPipeline",'+
'"https://github.com/TeamErlich/dna-fountain",'+
'"https://github.com/TheaWhitman/PyOM",'+
'"https://github.com/ThomasMiconi/BiologicallyPlausibleLearningRNN",'+
'"https://github.com/TommyBlanchard/StanNeuronModelling",'+
'"https://github.com/UCanCompBio/Avoidance",'+
'"https://github.com/UCanCompBio/deltaBS",'+
'"https://github.com/VCCRI/Falco/",'+
'"https://github.com/Washington-University/Pipelines",'+
'"https://github.com/WeiqiangZhou/BIRD",'+
'"https://github.com/WeitzGroup/DilutionMethod-NicheCompetition",'+
'"https://github.com/WeitzGroup/VMR-Lysis-Lysogeny",'+
'"https://github.com/WilsonSayresLab/MMB_apes",'+
'"https://github.com/WilsonSayresLab/PARdiversity",'+
'"https://github.com/WinawerLab/BOLD_LFP",'+
'"https://github.com/YosefLab/FastProject/",'+
'"https://github.com/YosefLab/TRAPeS",'+
'"https://github.com/Yves-CHEN/sCNAphase",'+
'"https://github.com/ZhiGroup/RaPID",'+
'"https://github.com/ZhuangLab/storm-analysis",'+
'"https://github.com/a-teufel/Accelerated_Sim",'+
'"https://github.com/abehr/pong",'+
'"https://github.com/ablab/mgra/",'+
'"https://github.com/abrown25/qvalue",'+
'"https://github.com/ackman678/wholeBrainDX",'+
'"https://github.com/ad3002/Cookiecutter",'+
'"https://github.com/adamallo/SimPhy",'+
'"https://github.com/adamewing/bamsurgeon",'+
'"https://github.com/adaptivegenome/clusterseq",'+
'"https://github.com/adrinjalali/Network-Classifier",'+
'"https://github.com/adsteen/enzalyze",'+
'"https://github.com/aivelo/lemur-community",'+
'"https://github.com/alanzos/ExInAtor/",'+
'"https://github.com/aldro61/kover/",'+
'"https://github.com/alegarra/metafounders",'+
'"https://github.com/alexviiia/dpuc2",'+
'"https://github.com/alizrrao/DepthOfCoveragePerInterval",'+
'"https://github.com/alyssafrazee/polyester",'+
'"https://github.com/amirrezaw/automagic",'+
'"https://github.com/amkozlov/sativa",'+
'"https://github.com/ammodramus/coalseam",'+
'"https://github.com/andreagobbi/pyBiRewire",'+
'"https://github.com/andreas-schlicker/OncoScape",'+
'"https://github.com/andyljones/NeuralNetworkMicroarraySegmentation",'+
'"https://github.com/ansariazim/TreeBreaker",'+
'"https://github.com/araksm/ceRNA/",'+
'"https://github.com/ariutta/svg-pan-zoom",'+
'"https://github.com/arlin/PenG_and_GLin",'+
'"https://github.com/arokem/att_ss",'+
'"https://github.com/arq5x/bedtools",'+
'"https://github.com/arq5x/nanopore-scripts",'+
'"https://github.com/arq5x/poretools",'+
'"https://github.com/aryeelab/diffloop_paper/",'+
'"https://github.com/asifrim/mrmosaic",'+
'"https://github.com/asncd/schimera",'+
'"https://github.com/atifrahman/SWALO/tree/scripts",'+
'"https://github.com/atredennick/Coexistence-Stability",'+
'"https://github.com/au-bios/python-landscapegen",'+
'"https://github.com/babelomics/hipathia",'+
'"https://github.com/baharpan/cosmo/tree/positional",'+
'"https://github.com/bahlolab/isoRelate",'+
'"https://github.com/baillielab/coexpression/",'+
'"https://github.com/balicea/RNA-discrete-dynamical-modeling",'+
'"https://github.com/barricklab/breseq",'+
'"https://github.com/bartongroup/AlmostSignificant",'+
'"https://github.com/bbimber/discvr-seq/",'+
'"https://github.com/benaug/SCRRcpp",'+
'"https://github.com/benfulcher/hctsa",'+
'"https://github.com/benjaminhgood/mutator_simulations",'+
'"https://github.com/benjjneb/dada2",'+
'"https://github.com/bensassonlab/scripts",'+
'"https://github.com/bensassonlab/yeastecology/",'+
'"https://github.com/bensutherland/salp_anon_to_sfon",'+
'"https://github.com/benwilson87/evolutionary-rescue-soft-sweeps",'+
'"https://github.com/bergmanlab/mcclintock",'+
'"https://github.com/bhklab/DNF",'+
'"https://github.com/bhklab/DrugTissue",'+
'"https://github.com/bhklab/EpiStroma-webapp",'+
'"https://github.com/bhklab/MetaGxData",'+
'"https://github.com/bihealth/hlama",'+
'"https://github.com/binarybottle/roygbiv",'+
'"https://github.com/binaypanda/RNAtor",'+
'"https://github.com/bioinfo-ut/GenomeTester4/",'+
'"https://github.com/bioinfonm/microBat",'+
'"https://github.com/bioinformatics-centre/kaiju",'+
'"https://github.com/bjornwallner/proteus",'+
'"https://github.com/blasseigne/ProliferativeIndex",'+
'"https://github.com/blekhmanlab/hominid",'+
'"https://github.com/bmbolstad/affyio",'+
'"https://github.com/bmbolstad/preprocessCore",'+
'"https://github.com/bmvdgeijn/WASP/",'+
'"https://github.com/bomeara/phrapl",'+
'"https://github.com/bondlab/scripts",'+
'"https://github.com/bradleylab/DsrAB_enzyme_models",'+
'"https://github.com/brandonlind/whitebark_pine",'+
'"https://github.com/brielin/popcorn",'+
'"https://github.com/bsipos/paper-pasp",'+
'"https://github.com/bulik/ldsc",'+
'"https://github.com/bulik/ldsc/",'+
'"https://github.com/bxlab/hifive",'+
'"https://github.com/cBioLab/sWM",'+
'"https://github.com/cancergenetics/cancergd",'+
'"https://github.com/cangermueller/deepcpg",'+
'"https://github.com/canlab/MediationToolbox",'+
'"https://github.com/canlab/RobustToolbox",'+
'"https://github.com/carolinecolijn/treetop",'+
'"https://github.com/carpenterlab/2016_pawlowski_mlcb",'+
'"https://github.com/carpenterlab/2016_rohban_submitted ",'+
'"https://github.com/carringtonlab/TargetFinder",'+
'"https://github.com/cashalow/teleost-radiation",'+
'"https://github.com/cashoes/enumerateblood",'+
'"https://github.com/catavallejos/BASiCS",'+
'"https://github.com/catmaid/CATMAID",'+
'"https://github.com/cbahlai/lampyrid/",'+
'"https://github.com/cbg-ethz/SCITE",'+
'"https://github.com/cboettig/appl",'+
'"https://github.com/ccraddock/afni",'+
'"https://github.com/ccshao/maIHB",'+
'"https://github.com/cfriedline/foxtail_wue",'+
'"https://github.com/cggh/panoptes",'+
'"https://github.com/champost/ABLE",'+
'"https://github.com/chapmanb/bcbio-nextgen",'+
'"https://github.com/chedonat/OncoPhase",'+
'"https://github.com/chiasto/hyRAD",'+
'"https://github.com/chiulab/MetaPORE",'+
'"https://github.com/chiulab/surpi",'+
'"https://github.com/choderalab/dispensing-errors-manuscript",'+
'"https://github.com/choderalab/ensembler",'+
'"https://github.com/choderalab/itc-worksheet",'+
'"https://github.com/chr1swallace/GUESSFM",'+
'"https://github.com/chr1swallace/TibsPower",'+
'"https://github.com/chrisamiller/fishplot",'+
'"https://github.com/chrisquince/DESMAN",'+
'"https://github.com/churchill-lab/gbrs",'+
'"https://github.com/churchlab/optmage",'+
'"https://github.com/cianodonnell/PopulationTracking",'+
'"https://github.com/cidvbi/PathogenPortal",'+
'"https://github.com/ckinzthompson/biasd",'+
'"https://github.com/clawpack/riemann",'+
'"https://github.com/cmagnabosco/OmicPipelines",'+
'"https://github.com/cmu-phil/tetrad",'+
'"https://github.com/common-workflow-language/common-workflow-language",'+
'"https://github.com/coreymhudson/AffyDistance",'+
'"https://github.com/cortex-lab/Suite2P",'+
'"https://github.com/counsyl/hgvs",'+
'"https://github.com/counsyl/sscm",'+
'"https://github.com/crs4/pyEHR",'+
'"https://github.com/crs4/rapi",'+
'"https://github.com/crukci-bioinformatics/camcAPP",'+
'"https://github.com/ctlab/fgsea",'+
'"https://github.com/cuttlefishh/papers",'+
'"https://github.com/dad/mrna-prot",'+
'"https://github.com/danielriosgarza/Bottom_Up_Ecology_Functions",'+
'"https://github.com/danilinares/2016LinaresLopezmoliner",'+
'"https://github.com/danimag/tkrelated",'+
'"https://github.com/danlwarren/RWTY",'+
'"https://github.com/datajoint/datajoint-matlab",'+
'"https://github.com/davek44/Basset",'+
'"https://github.com/david940408/CAMer",'+
'"https://github.com/davidaknowles/eagle",'+
'"https://github.com/davidaknowles/leafcutter",'+
'"https://github.com/davidrasm/PairTree",'+
'"https://github.com/dcjones/isolator",'+
'"https://github.com/ddarriba/partitiontest",'+
'"https://github.com/ddofer/asap",'+
'"https://github.com/debbiemarkslab/plmc",'+
'"https://github.com/deboraycb/reliability_hla_1000g",'+
'"https://github.com/dereneaton/virentes",'+
'"https://github.com/devosoft/avida",'+
'"https://github.com/deweylab/metasra-pipeline",'+
'"https://github.com/dg13/rasqual/",'+
'"https://github.com/dhimmel/hetio",'+
'"https://github.com/dhkron/PSYCHIC",'+
'"https://github.com/dimenwarper/gett",'+
'"https://github.com/dipetkov/eems",'+
'"https://github.com/diriano/ploidyNGS",'+
'"https://github.com/distancedevelopment/readdst",'+
'"https://github.com/dkoslicki/EMDeBruijn",'+
'"https://github.com/dlampart/csrproject",'+
'"https://github.com/dmlc/mxnet",'+
'"https://github.com/dohalloran/phylo-node",'+
'"https://github.com/donkeyshot/phybreak",'+
'"https://github.com/doricke/Divergence",'+
'"https://github.com/doricke/IBio",'+
'"https://github.com/douglasgscofield/add-to-Qiime-DB",'+
'"https://github.com/dsjohnson/multAbund",'+
'"https://github.com/dspeyer/ubiq_genome",'+
'"https://github.com/dufourya/SwimTracker",'+
'"https://github.com/ebov/space-time",'+
'"https://github.com/egeeamu/voskhod",'+
'"https://github.com/eiriniar/CellCnn",'+
'"https://github.com/ekg/freebayes",'+
'"https://github.com/ekg/glia",'+
'"https://github.com/eliotmiller/metricTester",'+
'"https://github.com/elzbth/ChromoViz",'+
'"https://github.com/emjosephs/eQTL",'+
'"https://github.com/emreg00/proxide",'+
'"https://github.com/enormandeau/mapcomp/",'+
'"https://github.com/episurg/episurg",'+
'"https://github.com/ericschulz/contextualbandits",'+
'"https://github.com/eriqande/gaiah",'+
'"https://github.com/eriqande/wiwa-popgen",'+
'"https://github.com/erscott/RASLseqTools",'+
'"https://github.com/esbeneickhardt/TFBSAnnotator",'+
'"https://github.com/evocellnet/ksea",'+
'"https://github.com/faircloth-lab/phyluce/",'+
'"https://github.com/faircloth-lab/radcap",'+
'"https://github.com/fairmiracle/AMOUNTAIN",'+
'"https://github.com/famulare/howPolioVaccinationAffectsPoliovirusTransmission",'+
'"https://github.com/fbreitwieser/pavian",'+
'"https://github.com/fchollet/keras",'+
'"https://github.com/fgvieira/ngsF",'+
'"https://github.com/finkelsteinlab/fylm",'+
'"https://github.com/fjhheras/phhotoreceptor",'+
'"https://github.com/flass/agrogenom",'+
'"https://github.com/fliem/LIFE_RS_preprocessing",'+
'"https://github.com/francescojm/SLAPenrich",'+
'"https://github.com/fraser-lab/EMRinger",'+
'"https://github.com/fraser-lab/PUBS2014",'+
'"https://github.com/fritzsedlazeck/SURVIVOR",'+
'"https://github.com/fukunagatsu/RIblast",'+
'"https://github.com/fusaroli/AcousticPatternsInASD",'+
'"https://github.com/fvandin/ExaLT",'+
'"https://github.com/fxia22/HINGE",'+
'"https://github.com/ga4gh/schemas",'+
'"https://github.com/gabraham/flashpca",'+
'"https://github.com/gangwug/MetaCycle",'+
'"https://github.com/gaoshanT/Fastq_clean",'+
'"https://github.com/gauravbhatia1/PCGCRegression",'+
'"https://github.com/gbradburd/SpaceMix",'+
'"https://github.com/geneva/POPBAMTools",'+
'"https://github.com/genome/bam-readcount",'+
'"https://github.com/genomecuration/JAMg",'+
'"https://github.com/genoo/GenOO",'+
'"https://github.com/gersteinlab/HiC_spector",'+
'"https://github.com/gersteinlab/MrTADFinder",'+
'"https://github.com/gilles-didier/TDALP",'+
'"https://github.com/giorap/tv-plots",'+
'"https://github.com/giraola/KARL",'+
'"https://github.com/gmiaslab/mathiomica",'+
'"https://github.com/goeckslab/isoseq-browser",'+
'"https://github.com/gpu-pdl-nudt/GeRelion",'+
'"https://github.com/greenelab/DAPS",'+
'"https://github.com/greenelab/adage",'+
'"https://github.com/greenelab/continuous_analysis",'+
'"https://github.com/greenelab/nf1_inactivation",'+
'"https://github.com/greenelab/tad_pathways",'+
'"https://github.com/grocsvs/grocsvs",'+
'"https://github.com/grunwaldlab/metacoder",'+
'"https://github.com/guigolab/CRISPETA",'+
'"https://github.com/ha0ye/rEDM",'+
'"https://github.com/hacone/AgIn",'+
'"https://github.com/hagenaue/BrainInABlender",'+
'"https://github.com/hailianghuang/efficientPCA",'+
'"https://github.com/hakyimlab/MetaXcan",'+
'"https://github.com/hakyimlab/PrediXcan",'+
'"https://github.com/hall-lab/svtyper",'+
'"https://github.com/hammerlab/pileup.js",'+
'"https://github.com/hammerlab/topeology",'+
'"https://github.com/hclimente/smartas",'+
'"https://github.com/hdetering/discomark",'+
'"https://github.com/health1987/dist",'+
'"https://github.com/hemberg-lab/D3E",'+
'"https://github.com/hesselberthlab/modmap",'+
'"https://github.com/hewittlab/Crossbow-GCE-Hadoop",'+
'"https://github.com/hitbc/deSPI",'+
'"https://github.com/hly89/FIMMCherry",'+
'"https://github.com/hmatsu1226/SCODE",'+
'"https://github.com/hmorlon/PANDA",'+
'"https://github.com/homopolymer/PyroTools",'+
'"https://github.com/huizhangucas/CISD",'+
'"https://github.com/huwenboshi/ImpG",'+
'"https://github.com/hzi-bifo/traitar",'+
'"https://github.com/iPlantCollaborativeOpenSource/iplant-agave-sdk",'+
'"https://github.com/iamciera/sister-of-pin1-material",'+
'"https://github.com/ibartomeus/RE_traits",'+
'"https://github.com/ibartomeus/powerlines",'+
'"https://github.com/ibest/ARC",'+
'"https://github.com/ihh/dnastore",'+
'"https://github.com/ikwak2/funqtl",'+
'"https://github.com/institut-de-genomique/MaGuS",'+
'"https://github.com/interCM/evolution",'+
'"https://github.com/ipw012/RIVER",'+
'"https://github.com/iqbal-lab/cortex",'+
'"https://github.com/iqbal-lab/gramtools",'+
'"https://github.com/isovic/graphmap",'+
'"https://github.com/jacobian1980/pfmix",'+
'"https://github.com/jade-cheng/ohana",'+
'"https://github.com/jamescrall/BEEtag",'+
'"https://github.com/jamesliley/subtest",'+
'"https://github.com/jameslyons/python_speech_features",'+
'"https://github.com/jasonsahl/UGAP",'+
'"https://github.com/jasperlinthorst/REVEAL",'+
'"https://github.com/jbloomlab/reedmuenchcalculator",'+
'"https://github.com/jbyoder/mutualism-sanctions-recognition",'+
'"https://github.com/jcarrotzhang/LoLoPicker",'+
'"https://github.com/jdiedrichsen/pcm_toolbox",'+
'"https://github.com/jedick/canprot",'+
'"https://github.com/jeetsukumaran/archipelago",'+
'"https://github.com/jeparson/mixtureprocesscontrol",'+
'"https://github.com/jeremymcrae/denovoFilter",'+
'"https://github.com/jeromekelleher/msprime-paper",'+
'"https://github.com/jgurtowski/nanocorr",'+
'"https://github.com/jhawkey/IS_mapper",'+
'"https://github.com/jhcepas/emapper-benchmark",'+
'"https://github.com/jijiadong/JDINAC",'+
'"https://github.com/jimhester/knitrBootstrap",'+
'"https://github.com/jimhester/primerTree",'+
'"https://github.com/jkenney9a/Zebrafish",'+
'"https://github.com/jmacdona/B_megaterium_modelling",'+
'"https://github.com/joebathelt/ZDHHC9_connectome",'+
'"https://github.com/joelhsmth/startmrca",'+
'"https://github.com/joepickrell/1000-genomes",'+
'"https://github.com/joewandy/HDP-Align",'+
'"https://github.com/jorruior/CIPHER",'+
'"https://github.com/josephryan/reduce_refseq",'+
'"https://github.com/joshuabhk/methylsuite",'+
'"https://github.com/jotwin/coevolution",'+
'"https://github.com/jpritt/boiler",'+
'"https://github.com/jsharbrough/grabContigs",'+
'"https://github.com/jsilve24/philr",'+
'"https://github.com/jstapleton/synthetic_reads",'+
'"https://github.com/jstjohn/SeqPrep",'+
'"https://github.com/jstjohn/SimSeq",'+
'"https://github.com/jts/nanopore-paper-analysis",'+
'"https://github.com/julien-roux/Roux_Liu_and_Robinson-Rechavi_2016",'+
'"https://github.com/julienfumey/popsim",'+
'"https://github.com/jyu429/IGHV-genotyping",'+
'"https://github.com/kaazemi/FCSS",'+
'"https://github.com/kakitone/BIGMAC",'+
'"https://github.com/kalleknast/head-tracker",'+
'"https://github.com/karl616/gNOMePeaks",'+
'"https://github.com/kassambara/easyGgplot2",'+
'"https://github.com/katholt/Kaptive",'+
'"https://github.com/katholt/RedDog",'+
'"https://github.com/katholt/srst2",'+
'"https://github.com/kauralasoo/rasqual",'+
'"https://github.com/kauralasoo/reviseAnnotations",'+
'"https://github.com/kbhoehn/IgPhyML",'+
'"https://github.com/kbroman/simcross",'+
'"https://github.com/kc-lab/dms2dfe",'+
'"https://github.com/kdmurray91/kwip",'+
'"https://github.com/kern-lab/discoal",'+
'"https://github.com/kern-lab/discoal_multipop",'+
'"https://github.com/kern-lab/shIC",'+
'"https://github.com/khayer/benchmarking_scripts",'+
'"https://github.com/khramts/assocplots",'+
'"https://github.com/kieranrcampbell/embeddr",'+
'"https://github.com/kieranrcampbell/gpseudotime",'+
'"https://github.com/kieranrcampbell/ouija",'+
'"https://github.com/kkdey/CountClust",'+
'"https://github.com/kloetzl/biotwiddle",'+
'"https://github.com/koadman/longas",'+
'"https://github.com/konradjk/exac_browser",'+
'"https://github.com/konradjk/loftee",'+
'"https://github.com/ksahlin/BESST",'+
'"https://github.com/ksahlin/GetDistr",'+
'"https://github.com/kshitijtayal/GPhase/",'+
'"https://github.com/ktrappe/daisy",'+
'"https://github.com/kundajelab/dragonn",'+
'"https://github.com/kundajelab/keras/tree/keras_1",'+
'"https://github.com/kvougas/Vougas_DeepLearning",'+
'"https://github.com/kwikteam/klustakwik2/",'+
'"https://github.com/lamarck2008/LEM",'+
'"https://github.com/lanagarmire/SSrGE",'+
'"https://github.com/lanagarmire/cox-nnet",'+
'"https://github.com/laurenemberson/EmbersonZinszerMCPA_analysesFromPaper",'+
'"https://github.com/lauringlab/variant_pipeline",'+
'"https://github.com/lbaeten/DivChangeResponse",'+
'"https://github.com/leekgroup/genesigprecision",'+
'"https://github.com/leekgroup/recount",'+
'"https://github.com/leffj/mctoolsr",'+
'"https://github.com/lengning/OEFinder",'+
'"https://github.com/lengning/SCPattern",'+
'"https://github.com/lganel/SVScore",'+
'"https://github.com/lh3/bgt",'+
'"https://github.com/lh3/seqtk",'+
'"https://github.com/lh3/wgsim",'+
'"https://github.com/lhhunghimself/fastBMA",'+
'"https://github.com/lhhunghimself/fast_protein_cluster",'+
'"https://github.com/limno/illumitag/",'+
'"https://github.com/linsalrob/qudaich/",'+
'"https://github.com/linzx06/AC-PCA",'+
'"https://github.com/llerussell/paq2py",'+
'"https://github.com/lmweber/cytometry-clustering-comparison",'+
'"https://github.com/local-minimum/scanomatic/",'+
'"https://github.com/loire/GalapagosData_And_Script/",'+
'"https://github.com/lomereiter/sambamba",'+
'"https://github.com/lorinanthony/MEPIT",'+
'"https://github.com/lsncibb/microbiomeGWAS",'+
'"https://github.com/lstevison/great-ape-recombination/",'+
'"https://github.com/lucapinello/CRISPResso",'+
'"https://github.com/luoyunan/DTINet",'+
'"https://github.com/lutzfischer/xiFDR",'+
'"https://github.com/lvdmaaten/bhtsne/",'+
'"https://github.com/lwlss/Holstein2016",'+
'"https://github.com/lyd0527/mInDel",'+
'"https://github.com/ma-compbio/Weaver",'+
'"https://github.com/machenslab/dPCA",'+
'"https://github.com/machinegun/hi-c-scaffold",'+
'"https://github.com/magicDGS/ReadTools",'+
'"https://github.com/mahyam/DNA-methylation-and-metabolism-R-code",'+
'"https://github.com/mailund/IMCoalHMM",'+
'"https://github.com/mailund/admixture_graph",'+
'"https://github.com/maljoras/xyTracker",'+
'"https://github.com/marbl/canu",'+
'"https://github.com/marbl/harvest",'+
'"https://github.com/marbl/mash",'+
'"https://github.com/marcottelab/Gene-Ages",'+
'"https://github.com/marcottelab/boolean",'+
'"https://github.com/marcottelab/protein_complex_maps_public",'+
'"https://github.com/marcus1487/nanoraw",'+
'"https://github.com/marianattestad/assemblytics",'+
'"https://github.com/markrobinsonuzh/benchmarkR",'+
'"https://github.com/markrobinsonuzh/diff_splice_paper",'+
'"https://github.com/markrobinsonuzh/iCOBRA",'+
'"https://github.com/martinosorb/herding-spikes",'+
'"https://github.com/marvinboe/reTASEP",'+
'"https://github.com/mathii/spectrum",'+
'"https://github.com/mbdoud/Compare-NP-Preferences",'+
'"https://github.com/mbontrager/primate_ca",'+
'"https://github.com/mdcao/npScarf",'+
'"https://github.com/medvedevgroup/bloomtree-allsome",'+
'"https://github.com/medvedevgroup/varmatch",'+
'"https://github.com/melodi-lab/submodular-selection-of-assays",'+
'"https://github.com/melop/admixem",'+
'"https://github.com/mendessoares/MMinte",'+
'"https://github.com/meren/reads-for-assembly",'+
'"https://github.com/merenlab/illumina-utils",'+
'"https://github.com/mevers/RNAModR",'+
'"https://github.com/mfcovington/SNPtools",'+
'"https://github.com/mfcovington/snps-from-rils",'+
'"https://github.com/mg14/AML-multistage",'+
'"https://github.com/mgonzalezporta/SwitchSeq",'+
'"https://github.com/middleprofessor/happiness",'+
'"https://github.com/mikel-egana-aranguren/SADI-Galaxy",'+
'"https://github.com/millanek/fineRADstructure",'+
'"https://github.com/millanek/trio-sga",'+
'"https://github.com/mills-lab/spectre",'+
'"https://github.com/min110/mislabeled.samples.identification",'+
'"https://github.com/mlandis/biogeo_dating",'+
'"https://github.com/mleibman/SlickGrid/",'+
'"https://github.com/mlin/PhyloCSF/",'+
'"https://github.com/mmatschiner/F4",'+
'"https://github.com/mobleylab/benchmarksets",'+
'"https://github.com/molgenis/gavin",'+
'"https://github.com/molgenis/molgenis-pipelines",'+
'"https://github.com/molpopgen/msstats",'+
'"https://github.com/morinlab/tools-morinlab",'+
'"https://github.com/mourisl/Lighter/",'+
'"https://github.com/mpdunne/orthofiller",'+
'"https://github.com/mreppell/Karp",'+
'"https://github.com/mrhunsaker/Change_Point",'+
'"https://github.com/mrmckain/AJB_2015_Mimulus_Allopolyploidy",'+
'"https://github.com/mrmckain/FASTKs",'+
'"https://github.com/msettles/dbcAmplicons",'+
'"https://github.com/msproteomicstools/msproteomicstools",'+
'"https://github.com/mtw/Bio-ViennaNGS",'+
'"https://github.com/muhligs/regmex",'+
'"https://github.com/murphycj/AGFusion",'+
'"https://github.com/mvboven/cmv-serology",'+
'"https://github.com/mw55309/poRe_docs",'+
'"https://github.com/mzwiessele/topslam",'+
'"https://github.com/najoshi/sabre",'+
'"https://github.com/najoshi/sickle",'+
'"https://github.com/narechan/clusterflock",'+
'"https://github.com/naturalis/imgpheno",'+
'"https://github.com/nedelec/cytosim",'+
'"https://github.com/nelas/color-blind-luts",'+
'"https://github.com/nellore/rail-dbgap",'+
'"https://github.com/nellore/runs",'+
'"https://github.com/nerobbin/20161214_hydropatterning",'+
'"https://github.com/neurosynth/neurosynth",'+
'"https://github.com/nghiavtr/ISOP",'+
'"https://github.com/nh13/DWGSIM/",'+
'"https://github.com/nignatiadis/ihwPaper",'+
'"https://github.com/nipy/PySurfer",'+
'"https://github.com/nluhmann/AGapEs",'+
'"https://github.com/nmdavies/UKbiobankROSLA",'+
'"https://github.com/nmdp-bioinformatics/genotype-list",'+
'"https://github.com/nvalimak/fsm-lite",'+
'"https://github.com/ohnosequences/mg7",'+
'"https://github.com/oicr-gsi/debarcer",'+
'"https://github.com/opetchey/ecopredtools",'+
'"https://github.com/orrzor/2016_NP_MxA_paper",'+
'"https://github.com/pachterlab/PROBer_paper_analysis",'+
'"https://github.com/pachterlab/bears_analyses",'+
'"https://github.com/pachterlab/zika/",'+
'"https://github.com/pagnani/PlmDCA",'+
'"https://github.com/pandegroup/openmm",'+
'"https://github.com/pandegroup/pdbfixer",'+
'"https://github.com/pasculorente/Mist",'+
'"https://github.com/paula-tataru/SpikeyTree",'+
'"https://github.com/pberkes/neuro-kl",'+
'"https://github.com/pblischak/polyfreqs-ms-data",'+
'"https://github.com/pedroj/MS_Network-Sampling",'+
'"https://github.com/pennekampster/bemovi",'+
'"https://github.com/petercombs/EisenLab-Code",'+
'"https://github.com/petrelharp/euroibd",'+
'"https://github.com/petrelharp/local_pca",'+
'"https://github.com/pgnelson/emergent_capacitance",'+
'"https://github.com/phac-nml/neptune",'+
'"https://github.com/phrh/PredRAD",'+
'"https://github.com/pierpal/ARGON",'+
'"https://github.com/pillowlab/CDMentropy",'+
'"https://github.com/pillowlab/StepRampMCMC",'+
'"https://github.com/piquelab/QuASAR",'+
'"https://github.com/pkerpedjiev/forgi",'+
'"https://github.com/pmb59/fCCAC/",'+
'"https://github.com/poeli/GOTTCHA",'+
'"https://github.com/pomo-dev/PoMo",'+
'"https://github.com/pontikos/phenopolis",'+
'"https://github.com/popgenomics/popPhylABC",'+
'"https://github.com/ppgardne/RMfam",'+
'"https://github.com/prefixcommons/prefixes",'+
'"https://github.com/preprocessed-connectomes-project/adhd200_athena_scripts",'+
'"https://github.com/pshved/timeout",'+
'"https://github.com/pstew/escape_excel",'+
'"https://github.com/psychoinformatics-de/studyforrest-data-multires7t",'+
'"https://github.com/qfma/duf1220",'+
'"https://github.com/quantixed/PaperCode/",'+
'"https://github.com/r3fang/PLACseq",'+
'"https://github.com/rajanil/msCentipede",'+
'"https://github.com/rajewsky-lab/dropbead",'+
'"https://github.com/raquele/GeNNet",'+
'"https://github.com/rasilab/ferrin_1",'+
'"https://github.com/ratschlab/ribodiff",'+
'"https://github.com/ratschlab/spladder",'+
'"https://github.com/rcannood/SCORPIUS",'+
'"https://github.com/rdejonge/genomics",'+
'"https://github.com/rdiaz02/OncoSimul",'+
'"https://github.com/regulomics/biopython",'+
'"https://github.com/rhodricusack/automaticanalysis",'+
'"https://github.com/rhr/lagrange-cpp",'+
'"https://github.com/rich-iannone/stationaRy",'+
'"https://github.com/rlgoldfeder/coverageOfKeyGenes",'+
'"https://github.com/rmcclosk/netabc",'+
'"https://github.com/rmcelreath/parasiticbehaviorsim",'+
'"https://github.com/rohanmaddamsetti/Ara-1_Genotyping",'+
'"https://github.com/ropensci/rgbif",'+
'"https://github.com/rr1859/R.4Cker",'+
'"https://github.com/rrwick/Bandage",'+
'"https://github.com/rrwick/Unicycler",'+
'"https://github.com/rsbaucom/MatingSystem2015",'+
'"https://github.com/ruanjue/smartdenovo",'+
'"https://github.com/ruolin/Strawberry",'+
'"https://github.com/russcd/Ancestry_HMM",'+
'"https://github.com/rvaser/sword",'+
'"https://github.com/ryanlayer/gqt",'+
'"https://github.com/saemi/plast2phy",'+
'"https://github.com/saezlab/kinact/",'+
'"https://github.com/saezlab/liverx",'+
'"https://github.com/saezlab/yeast_phospho",'+
'"https://github.com/sahilseth/flowr",'+
'"https://github.com/samtools/BCFtools",'+
'"https://github.com/samtools/hts-specs/",'+
'"https://github.com/sandipchatterjee/blazmass_compil",'+
'"https://github.com/sandywang/GRETNA",'+
'"https://github.com/sanger-pathogens/vr-codebase",'+
'"https://github.com/sarahmid/PESS",'+
'"https://github.com/sarbal/EGAD",'+
'"https://github.com/sarisbro/AEGIS",'+
'"https://github.com/satoken/practip",'+
'"https://github.com/sbenz/Paradigm",'+
'"https://github.com/schatzlab/genomescope",'+
'"https://github.com/schlegelp/CATMAID-to-Blender",'+
'"https://github.com/secastel/aFC",'+
'"https://github.com/secastel/phaser",'+
'"https://github.com/seqcode/sequnwinder",'+
'"https://github.com/sequana/sequana",'+
'"https://github.com/seth-ament/hd-trn",'+
'"https://github.com/sggaffney/pathscore",'+
'"https://github.com/shahmoradi/cordiv",'+
'"https://github.com/shahpr/RiboViz",'+
'"https://github.com/sharpton/shotmap",'+
'"https://github.com/simongog/sdsl-lite",'+
'"https://github.com/simonvh/fluff",'+
'"https://github.com/sjczheng/EpiDISH",'+
'"https://github.com/sjspielman/pyvolve",'+
'"https://github.com/sknepneklab/SAMoS",'+
'"https://github.com/skumagai/selfingsim",'+
'"https://github.com/slisovski/Geolocator-ArcticWader-BreedingSiteEstimation",'+
'"https://github.com/smangul1/HapIso/",'+
'"https://github.com/smithmj/Antibiotic-Cycling",'+
'"https://github.com/smorfopoulou/metaMix",'+
'"https://github.com/snacktavish/TreeToReads",'+
'"https://github.com/snayfach/MIDAS",'+
'"https://github.com/snayfach/MicrobeCensus",'+
'"https://github.com/soccin/S1Seq",'+
'"https://github.com/soedinglab/BaMMmotif",'+
'"https://github.com/soedinglab/mmseqs2",'+
'"https://github.com/sofroniewn/2pRAM-paper",'+
'"https://github.com/sophie63/FlyLFM",'+
'"https://github.com/spacocha/Distribution-based-clustering",'+
'"https://github.com/spulido99/SSA",'+
'"https://github.com/spyder-ide/spyder",'+
'"https://github.com/sschmeier/irndb2",'+
'"https://github.com/stajichlab/FGMP",'+
'"https://github.com/stamatak/softwareQuality",'+
'"https://github.com/stamatak/standard-RAxML",'+
'"https://github.com/stamatak/tree-viz-issues",'+
'"https://github.com/statgen/verifyBamID",'+
'"https://github.com/stephaneguindon/phyml",'+
'"https://github.com/stephaniehicks/qsmooth",'+
'"https://github.com/stephaniehicks/quantroSim",'+
'"https://github.com/stephenfloor/tripseq-analysis",'+
'"https://github.com/stephens999/ashr",'+
'"https://github.com/stephenslab/mashr",'+
'"https://github.com/stephenslab/rss",'+
'"https://github.com/stephenturner/qqman",'+
'"https://github.com/stschiff/hfit",'+
'"https://github.com/stschiff/msmc2",'+
'"https://github.com/stschiff/rarecoal",'+
'"https://github.com/stuberlab/PC_opto_fMRI_analysis",'+
'"https://github.com/susjoh/crimaptools",'+
'"https://github.com/svviz/svviz",'+
'"https://github.com/sys-bio/sbnw",'+
'"https://github.com/sys-bio/simplesbml",'+
'"https://github.com/systems-immunology-roslin-institute/ImSig",'+
'"https://github.com/szpiech/selscan",'+
'"https://github.com/tanghaibao/goatools",'+
'"https://github.com/taoliu/MACS",'+
'"https://github.com/taoliu/MACS/tree/macs_v1",'+
'"https://github.com/tare/GPMicrobiome",'+
'"https://github.com/tarunaaggarwal/G.morbida.Comp.Gen",'+
'"https://github.com/tderrien/FEELnc",'+
'"https://github.com/tgouhier/biwavelet",'+
'"https://github.com/theis188/py_emra",'+
'"https://github.com/thh32/Spherical",'+
'"https://github.com/thierrygosselin/stackr",'+
'"https://github.com/thk2008/methylseqplatformcomparison",'+
'"https://github.com/tknijnen/LOBICO",'+
'"https://github.com/tkuhn/bel2nanopub/",'+
'"https://github.com/tombergk/FVL_SUP",'+
'"https://github.com/torognes/vsearch",'+
'"https://github.com/tracysmith/RGAPepPipe",'+
'"https://github.com/transcript/SAMSA",'+
'"https://github.com/trayc7/FDPPDIV",'+
'"https://github.com/trgao10/PuenteAlignment",'+
'"https://github.com/tsackton/musca-immunity",'+
'"https://github.com/tseemann/abricate",'+
'"https://github.com/tseemann/snippy",'+
'"https://github.com/tshmak/lassosum",'+
'"https://github.com/tslumley/bigQF",'+
'"https://github.com/ttesileanu/twostagelearning",'+
'"https://github.com/twestbrookunh/paladin",'+
'"https://github.com/uci-cbcl/D-GEX",'+
'"https://github.com/uci-cbcl/HLA-bind",'+
'"https://github.com/ueser/FIDDLE",'+
'"https://github.com/ugcd/solarius",'+
'"https://github.com/umutcaglar/ecoli_multiple_growth_conditions",'+
'"https://github.com/uriba/proteome-analysis",'+
'"https://github.com/valafarlab/biodiff",'+
'"https://github.com/varnerlab/POETs.jl",'+
'"https://github.com/vcflib/vcflib",'+
'"https://github.com/vegandevs/vegan",'+
'"https://github.com/vgteam/vg",'+
'"https://github.com/vistalab/vistasoft",'+
'"https://github.com/vqv/ggbiplot",'+
'"https://github.com/wacguy/Simple",'+
'"https://github.com/waldronlab/curatedMetagenomicData/",'+
'"https://github.com/wassermanlab/CAGEd-oPOSSUM",'+
'"https://github.com/weikanggong/BWAS",'+
'"https://github.com/wenjiegroup/PEDLA",'+
'"https://github.com/wiheto/teneto",'+
'"https://github.com/wilkelab/eGFP_deletion_prediction",'+
'"https://github.com/wilkelab/influenza_H3N2_passaging",'+
'"https://github.com/wingolab-org/pecaller",'+
'"https://github.com/xapple/seqenv",'+
'"https://github.com/xavierdidelot/TransPhylo",'+
'"https://github.com/xiangfstats/GenieR",'+
'"https://github.com/xiaochuanle/MECAT",'+
'"https://github.com/xjwanglab/pyrl",'+
'"https://github.com/xqwen/dap",'+
'"https://github.com/xqwen/integrative/",'+
'"https://github.com/xqwen/torus/",'+
'"https://github.com/xuebingwu/kpLogo",'+
'"https://github.com/xypan1232/iDeep",'+
'"https://github.com/yangzhi-psy/gRAICAR",'+
'"https://github.com/yifeng-li/DECRES",'+
'"https://github.com/yiminghu/AnnoPred",'+
'"https://github.com/yjingj/SFBA",'+
'"https://github.com/ymatts/D3M/",'+
'"https://github.com/ymatts/phyC",'+
'"https://github.com/yoheirosen/vg",'+
'"https://github.com/yuelab/BUTLRTools",'+
'"https://github.com/z0on/GO_MWU",'+
'"https://github.com/z0on/tag-based_RNAseq",'+
'"https://github.com/zdealveindy/weimea/",'+
'"https://github.com/zeux/pugixml",'+
'"https://github.com/zhandong/XMRF",'+
'"https://github.com/zhangsaithu/tide_demo",'+
'"https://github.com/zhouxiaofan1983/iWGS",'+
'"https://github.com/zibraproject/zika-pipeline",'+
'"https://github.com/zuoxinian/CCS",'+
'"https://github.com/zyndagj/repliscan"]'+
'}';

// define the switcher
var repo = require('../lib/switcher');
var bioRepos = JSON.parse(text);

console.log("#BioRepoUrl"+"\t"+"Watchers"+"\t"+"Stars"+"\t"+"Forks"+"\t"+"Commits"+"\t"+"Branches"+"\t"+"Languages"+"\t"+"LanguagePercentages");
for(i=0; i<bioRepos.brepos.length; i++){
	repo(bioRepos.brepos[i], function(err, stats) {
		if(stats.watchers == ""){
			stats.watchers = "NAN";
		}
		if(stats.stars == ""){
			stats.stars = "NAN";
		}
		if(stats.forks == ""){
			stats.forks = "NAN";
		}
		if(stats.commits == ""){
			stats.commits = "NAN";
		}
		if(stats.branches == ""){
			stats.branches = "NAN";
		}
		process.stdout.write(stats.url+"\t"+stats.watchers+"\t"+stats.stars+"\t"+stats.forks+"\t"+stats.commits+"\t"+stats.branches+"\t");
		if(stats.langs.length > 0){
			for(l=0; l<stats.langs.length; l++){
				var langString = stats.langs[l].split(" ");
				process.stdout.write(langString[0]+";");
			}
		}else{
			process.stdout.write("NAN");
		}
		process.stdout.write("\t");
		if(stats.langs.length > 0){
			for(l=0; l<stats.langs.length; l++){
				var langString = stats.langs[l].split(" ");
				process.stdout.write(langString[1]+";");
			}
		}else{
			process.stdout.write("NAN");
		}
		process.stdout.write("\n");
	})
}

