var text = '{ "orgs" :' +  
'[ "https://github.com/choderalab",'+
'"https://github.com/cmu-phil",'+
'"https://github.com/CellProfiler",'+
'"https://github.com/cggh",'+
'"https://github.com/chiulab",'+
'"https://github.com/CMPG",'+
'"https://github.com/bensassonlab",'+
'"https://github.com/BioDepot",'+
'"https://github.com/CobraLab",'+
'"https://github.com/canlab",'+
'"https://github.com/BigNeuron",'+
'"https://github.com/bahlolab",'+
'"https://github.com/CNSGenomics",'+
'"https://github.com/23andMe",'+
'"https://github.com/bhklab",'+
'"https://github.com/cbg-ethz",'+
'"https://github.com/bhklab",'+
'"https://github.com/bergmanlab",'+
'"https://github.com/biorack",'+
'"https://github.com/ctlab",'+
'"https://github.com/churchlab",'+
'"https://github.com/bihealth",'+
'"https://github.com/cdcepi",'+
'"https://github.com/biometry",'+
'"https://github.com/biocore",'+
'"https://github.com/BEAST2-Dev",'+
'"https://github.com/Brazelton-Lab",'+
'"https://github.com/bensassonlab",'+
'"https://github.com/COMBINE-lab",'+
'"https://github.com/CampagneLaboratory",'+
'"https://github.com/ColeLab",'+
'"https://github.com/ablab",'+
'"https://github.com/bhklab",'+
'"https://github.com/carringtonlab",'+
'"https://github.com/cidvbi",'+
'"https://github.com/cBioLab",'+
'"https://github.com/bhklab",'+
'"https://github.com/bxlab",'+
'"https://github.com/debbiemarkslab",'+
'"https://github.com/faircloth-lab",'+
'"https://github.com/Ensembl",'+
'"https://github.com/distancedevelopment",'+
'"https://github.com/Danko-Lab",'+
'"https://github.com/crukci-bioinformatics",'+
'"https://github.com/barricklab",'+
'"https://github.com/Cibiv",'+
'"https://github.com/choderalab",'+
'"https://github.com/CellProfiler",'+
'"https://github.com/CampagneLaboratory",'+
'"https://github.com/bioinformatics-centre",'+
'"https://github.com/bartongroup",'+
'"https://github.com/cancergenetics",'+
'"https://github.com/carpenterlab",'+
'"https://github.com/BioDepot",'+
'"https://github.com/churchill-lab",'+
'"https://github.com/AdelaideBioinfo",'+
'"https://github.com/carpenterlab",'+
'"https://github.com/BD2K-DDI",'+
'"https://github.com/babelomics",'+
'"https://github.com/canlab",'+
'"https://github.com/GeorgievLab",'+
'"https://github.com/greenelab",'+
'"https://github.com/genomecuration",'+
'"https://github.com/blachlylab",'+
'"https://github.com/aryeelab",'+
'"https://github.com/10XGenomics",'+
'"https://github.com/genoo",'+
'"https://github.com/fraser-lab",'+
'"https://github.com/AdelaideBioinfo",'+
'"https://github.com/EnvGen",'+
'"https://github.com/hammerlab",'+
'"https://github.com/drmaa-python",'+
'"https://github.com/choderalab",'+
'"https://github.com/BinPro",'+
'"https://github.com/faircloth-lab",'+
'"https://github.com/bioinfologics",'+
'"https://github.com/gersteinlab",'+
'"https://github.com/greenelab",'+
'"https://github.com/hall-lab",'+
'"https://github.com/BiologicalRecordsCentre",'+
'"https://github.com/guigolab",'+
'"https://github.com/hewittlab",'+
'"https://github.com/CGATOxford",'+
'"https://github.com/DecodeGenetics",'+
'"https://github.com/greenelab",'+
'"https://github.com/hitbc",'+
'"https://github.com/fraser-lab",'+
'"https://github.com/Illumina",'+
'"https://github.com/dmlc",'+
'"https://github.com/fengzhanglab",'+
'"https://github.com/ga4gh",'+
'"https://github.com/datajoint",'+
'"https://github.com/IlyaLab",'+
'"https://github.com/hzi-bifo",'+
'"https://github.com/genome",'+
'"https://github.com/GreallyLab",'+
'"https://github.com/iPlantCollaborativeOpenSource",'+
'"https://github.com/evocellnet",'+
'"https://github.com/hakyimlab",'+
'"https://github.com/goeckslab",'+
'"https://github.com/EpiStemNet",'+
'"https://github.com/grunwaldlab",'+
'"https://github.com/Illumina",'+
'"https://github.com/HudsonAlpha",'+
'"https://github.com/GenomicsCoreLeuven",'+
'"https://github.com/HullUni-bioinformatics",'+
'"https://github.com/hakyimlab",'+
'"https://github.com/hemberg-lab",'+
'"https://github.com/hammerlab",'+
'"https://github.com/deweylab",'+
'"https://github.com/crs4",'+
'"https://github.com/genome-in-a-bottle",'+
'"https://github.com/galaxyproject",'+
'"https://github.com/GreenleafLab",'+
'"https://github.com/greenelab",'+
'"https://github.com/QTB-HHU",'+
'"https://github.com/counsyl",'+
'"https://github.com/DworkinLab",'+
'"https://github.com/institut-de-genomique",'+
'"https://github.com/iontorrent",'+
'"https://github.com/WormLabCaltech",'+
'"https://github.com/gigascience",'+
'"https://github.com/kbase",'+
'"https://github.com/marcottelab",'+
'"https://github.com/PyProphet",'+
'"https://github.com/gersteinlab",'+
'"https://github.com/Kingsford-Group",'+
'"https://github.com/restful-open-annotation",'+
'"https://github.com/catmaid",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/LucksLab",'+
'"https://github.com/cortex-lab",'+
'"https://github.com/QuackenbushLab",'+
'"https://github.com/FRED-2",'+
'"https://github.com/LucksLab",'+
'"https://github.com/Illumina",'+
'"https://github.com/i5K",'+
'"https://github.com/The-Sequence-Ontology",'+
'"https://github.com/PsychoinformaticsLab",'+
'"https://github.com/ibest",'+
'"https://github.com/sequencing",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/kwikteam",'+
'"https://github.com/ICBI",'+
'"https://github.com/cutterlab",'+
'"https://github.com/SheffieldML",'+
'"https://github.com/soedinglab",'+
'"https://github.com/ENCODE-DCC",'+
'"https://github.com/potamomics-scripts",'+
'"https://github.com/prefixcommons",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/MicrosoftGenomics",'+
'"https://github.com/TGenNorth",'+
'"https://github.com/medvedevgroup",'+
'"https://github.com/pachterlab",'+
'"https://github.com/WilsonSayresLab",'+
'"https://github.com/rasilab",'+
'"https://github.com/chiulab",'+
'"https://github.com/counsyl",'+
'"https://github.com/clawpack",'+
'"https://github.com/devosoft",'+
'"https://github.com/marbl",'+
'"https://github.com/TGenNorth",'+
'"https://github.com/piquelab",'+
'"https://github.com/InouyeLab",'+
'"https://github.com/svviz",'+
'"https://github.com/neuroelectro",'+
'"https://github.com/marbl",'+
'"https://github.com/SheffieldML",'+
'"https://github.com/sknepneklab",'+
'"https://github.com/preprocessed-connectomes-project",'+
'"https://github.com/PMBio",'+
'"https://github.com/marcottelab",'+
'"https://github.com/pachterlab",'+
'"https://github.com/RealTimeGenomics",'+
'"https://github.com/trinityrnaseq",'+
'"https://github.com/mills-lab",'+
'"https://github.com/PitchInteractiveInc",'+
'"https://github.com/soedinglab",'+
'"https://github.com/stan-dev",'+
'"https://github.com/molgenis",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/varapp",'+
'"https://github.com/medvedevgroup",'+
'"https://github.com/valafarlab",'+
'"https://github.com/KordingLab",'+
'"https://github.com/StoreyLab",'+
'"https://github.com/COMBINE-lab",'+
'"https://github.com/machenslab",'+
'"https://github.com/NYU-BFX",'+
'"https://github.com/ebov",'+
'"https://github.com/stephenslab",'+
'"https://github.com/Oshlack",'+
'"https://github.com/nipy",'+
'"https://github.com/UCanCompBio",'+
'"https://github.com/rajewsky-lab",'+
'"https://github.com/phenoscape",'+
'"https://github.com/SpeciesFileGroup",'+
'"https://github.com/nipy",'+
'"https://github.com/neurosynth",'+
'"https://github.com/msproteomicstools",'+
'"https://github.com/ugcd",'+
'"https://github.com/merenlab",'+
'"https://github.com/MRC-CLIMB",'+
'"https://github.com/Nextomics",'+
'"https://github.com/preprocessed-connectomes-project",'+
'"https://github.com/WilsonSayresLab",'+
'"https://github.com/LarracuenteLab",'+
'"https://github.com/hesselberthlab",'+
'"https://github.com/team-pltb",'+
'"https://github.com/seqcode",'+
'"https://github.com/KiddLab",'+
'"https://github.com/pachterlab",'+
'"https://github.com/melodi-lab",'+
'"https://github.com/zibraproject",'+
'"https://github.com/VCCRI",'+
'"https://github.com/pandegroup",'+
'"https://github.com/McKinlab",'+
'"https://github.com/trinityrnaseq",'+
'"https://github.com/marbl",'+
'"https://github.com/limno",'+
'"https://github.com/msmbuilder",'+
'"https://github.com/NIHOPA",'+
'"https://github.com/schatzlab",'+
'"https://github.com/MarBL",'+
'"https://github.com/WagnerLabPapers",'+
'"https://github.com/ZhuangLab",'+
'"https://github.com/spyder-ide",'+
'"https://github.com/vcflib",'+
'"https://github.com/UCanCompBio",'+
'"https://github.com/systems-immunology-roslin-institute",'+
'"https://github.com/waldronlab",'+
'"https://github.com/pomo-dev",'+
'"https://github.com/ucscGenomeBrowser",'+
'"https://github.com/KarchinLab",'+
'"https://github.com/Illumina",'+
'"https://github.com/wingolab-org",'+
'"https://github.com/grocsvs",'+
'"https://github.com/oicr-gsi",'+
'"https://github.com/vistalab",'+
'"https://github.com/marcottelab",'+
'"https://github.com/stephenslab",'+
'"https://github.com/MRtrix3",'+
'"https://github.com/PF2-pasteur-fr",'+
'"https://github.com/sanger-pathogens",'+
'"https://github.com/saezlab",'+
'"https://github.com/phac-nml",'+
'"https://github.com/stuberlab",'+
'"https://github.com/greenelab",'+
'"https://github.com/StoreyLab",'+
'"https://github.com/Illumina",'+
'"https://github.com/jbloomlab",'+
'"https://github.com/lwlss",'+
'"https://github.com/LANL-Bioinformatics",'+
'"https://github.com/PMBio",'+
'"https://github.com/mobleylab",'+
'"https://github.com/NAL-i5K",'+
'"https://github.com/wilkelab",'+
'"https://github.com/vegandevs",'+
'"https://github.com/morinlab",'+
'"https://github.com/OSSCB2013",'+
'"https://github.com/sequana",'+
'"https://github.com/PMBio",'+
'"https://github.com/macmanes-lab",'+
'"https://github.com/common-workflow-language",'+
'"https://github.com/pandegroup",'+
'"https://github.com/kundajelab",'+
'"https://github.com/Kingsford-Group",'+
'"https://github.com/ModelSEED",'+
'"https://github.com/uci-cbcl",'+
'"https://github.com/lauringlab",'+
'"https://github.com/griffithlab",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/saezlab",'+
'"https://github.com/psychoinformatics-de",'+
'"https://github.com/NeuralEnsemble",'+
'"https://github.com/leekgroup",'+
'"https://github.com/KnowEnG",'+
'"https://github.com/PMBio",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/TGAC",'+
'"https://github.com/kundajelab",'+
'"https://github.com/uci-cbcl",'+
'"https://github.com/pillowlab",'+
'"https://github.com/SIMEXP",'+
'"https://github.com/YosefLab",'+
'"https://github.com/LohmuellerLab",'+
'"https://github.com/pillowlab",'+
'"https://github.com/wilkelab",'+
'"https://github.com/wassermanlab",'+
'"https://github.com/saezlab",'+
'"https://github.com/sys-bio",'+
'"https://github.com/SuLab",'+
'"https://github.com/samtools",'+
'"https://github.com/leekgroup",'+
'"https://github.com/molgenis",'+
'"https://github.com/statgen",'+
'"https://github.com/RGLab",'+
'"https://github.com/WinawerLab",'+
'"https://github.com/PacificBiosciences",'+
'"https://github.com/INCF",'+
'"https://github.com/MDU-PHL",'+
'"https://github.com/sys-bio",'+
'"https://github.com/WeitzGroup",'+
'"https://github.com/TeamErlich",'+
'"https://github.com/RGLab",'+
'"https://github.com/Washington-University",'+
'"https://github.com/samtools",'+
'"https://github.com/YosefLab",'+
'"https://github.com/nmdp-bioinformatics",'+
'"https://github.com/ropensci",'+
'"https://github.com/vgteam",'+
'"https://github.com/crs4",'+
'"https://github.com/WeitzGroup",'+
'"https://github.com/MPBA",'+
'"https://github.com/ratschlab",'+
'"https://github.com/NESCent",'+
'"https://github.com/LennonLab",'+
'"https://github.com/regulomics",'+
'"https://github.com/stajichlab",'+
'"https://github.com/ISA-tools",'+
'"https://github.com/ratschlab",'+
'"https://github.com/KHP-Informatics",'+
'"https://github.com/PriceLab",'+
'"https://github.com/naturalis",'+
'"https://github.com/ohnosequences"]'+
'}';

var scrapedOrgs = JSON.parse(text);

